Cell[BoxData[RowBox[{"Persist", "[", RowBox[{"\"trivialScene2D\"", ",", 
      "\[IndentingNewLine]", RowBox[{RowBox[{"NeedsDefined", "[", 
          RowBox[{"GridDataMakeFromArrays", ",", "Scene2DMake"}], "]"}], ";", 
        "\[IndentingNewLine]", "\[IndentingNewLine]", 
        RowBox[{"trivialScene2DA", "=", RowBox[{"Table", "[", 
            RowBox[{"1.", ",", "3", ",", "3"}], "]"}]}], ";", 
        "\[IndentingNewLine]", RowBox[{"trivialScene2DD", "=", 
          RowBox[{"1.", RowBox[{"{", RowBox[{RowBox[{"{", RowBox[{"1", ",", 
                    "1", ",", "1"}], "}"}], ",", RowBox[{"{", RowBox[
                   {"1", ",", "0", ",", "1"}], "}"}], ",", RowBox[
                 {"{", RowBox[{"1", ",", "1", ",", "1"}], "}"}]}], "}"}]}]}], 
        ";", "\[IndentingNewLine]", RowBox[{"trivialScene2Dl", "=", 
          RowBox[{"Normalize", "@", RowBox[{"{", RowBox[{"1.", ",", "1."}], 
              "}"}]}]}], ";", "\[IndentingNewLine]", 
        RowBox[{"trivialScene2DC", "=", RowBox[{"Table", "[", 
            RowBox[{"1.", ",", "3", ",", "3", ",", "3"}], "]"}]}], ";", 
        "\[IndentingNewLine]", "\[IndentingNewLine]", 
        RowBox[{"trivialScene2Dgd", "=", RowBox[{"GridDataMakeFromArrays", 
            "[", "\[IndentingNewLine]", RowBox[{RowBox[{"{", RowBox[
                 {"\"a\"", ",", "\"d\"", ",", "\"doriginal\"", ",", 
                  "\"c\""}], "}"}], ",", "\[IndentingNewLine]", 
              RowBox[{"{", RowBox[{"trivialScene2DA", ",", "trivialScene2DD", 
                  ",", "trivialScene2DD", ",", "trivialScene2DC"}], "}"}], 
              ",", "\[IndentingNewLine]", "2"}], "\[IndentingNewLine]", 
            "]"}]}], ";", "\[IndentingNewLine]", "\[IndentingNewLine]", 
        RowBox[{"trivialScene2D", "=", RowBox[{"Scene2DMake", "[", 
            RowBox[{"trivialScene2Dl", ",", "trivialScene2Dgd"}], "]"}]}], 
        ";"}]}], "\[IndentingNewLine]", "\[IndentingNewLine]", "]"}]], 
 "Input", CellChangeTimes -> {{3.6805635175748672*^9, 3.6805635276190147*^9}, 
   3.6805646345134687*^9, 3.680607980873057*^9, {3.6806080502195826*^9, 
    3.6806081136897635*^9}}, CellTags -> "depersistedCell"]
