Cell[BoxData[RowBox[{"Persist", "[", RowBox[{"\"trivialScene2DTests\"", ",", 
      "\[IndentingNewLine]", RowBox[{RowBox[{"NeedsDefined", "[", 
          "trivialScene2D", "]"}], ";", "\[IndentingNewLine]", 
        "\[IndentingNewLine]", "\[IndentingNewLine]", 
        RowBox[{"{", "\[IndentingNewLine]", RowBox[
           {RowBox[{"{", RowBox[{"(*", "*)"}], "\[IndentingNewLine]", 
              "\[IndentingNewLine]", ",", "\[IndentingNewLine]", 
              "\[IndentingNewLine]", "}"}], "\[IndentingNewLine]", 
            "\[IndentingNewLine]", "\[IndentingNewLine]", 
            "\[IndentingNewLine]", ",", "\[IndentingNewLine]", 
            RowBox[{"{", "}"}], ",", "\[IndentingNewLine]", 
            RowBox[{"{", "}"}], ",", "\[IndentingNewLine]", 
            RowBox[{"{", "}"}], ",", "\[IndentingNewLine]", 
            RowBox[{"{", "}"}], ","}], "\[IndentingNewLine]", "}"}]}]}], 
    "\[IndentingNewLine]", "\[IndentingNewLine]", "]"}]], "Input", 
 CellChangeTimes -> {{3.680609200926403*^9, 3.6806092601472826*^9}}, 
 CellTags -> "depersistedCellc7dbb792-81e2-4bec-a372-b1bae4a00ad9"]
