System`Cell[System`BoxData[System`RowBox[{"Block", "[", 
    System`RowBox[{System`RowBox[{"{", "}"}], ",", 
      System`RowBox[{"PTest", "[", System`RowBox[
         {System`RowBox[{"KeepMembersOf", "[", System`RowBox[
             {System`RowBox[{"{", System`RowBox[{"\"paul`\"", ",", 
                  "\"LocalGaussNewton`\"", ",", "\"varval`\"", ",", 
                  "\"cform`\"", ",", "\"FiniteMapping`\"", ",", 
                  "\"GridData`\"", ",", "\"PackageDeveloper`\"", ",", 
                  "\"CreateSymbol`\"", ",", "\"SymbolicC`\"", ",", 
                  "\"SOPCompiled`Private`\"", ",", 
                  "\"PackagePackage`Private`\"", ",", 
                  "\"CreateSymbol`Private`\"", ",", "\"SOPCompiled`\"", ",", 
                  "\"SOP`\"", ",", "\"SceneX`\"", ",", "\"Scene3D`\"", ",", 
                  "\"Scene2D`\"", ",", "\"RIFunction`\"", ",", 
                  "\"PackagePackage`\"", ",", "\"CreateSymbol`\"", ",", 
                  "\"ANewContext`\"", ",", "\"Persist`\"", ",", 
                  "\"RVarval`\"", ",", "\"numerics`\"", ",", "\"CUDALink`\"", 
                  ",", "\"GeneralUtilities`\"", ",", "\"CodeFormatter`\"", 
                  ",", "\"BoolEval`\"", ",", 
                  "\"SymbolicMachineLearningLoader`\"", ",", 
                  "\"StreamingLoader`\"", ",", "\"NeuralNetworks`\"", ",", 
                  "\"IconizeLoader`\"", ",", "\"HTTPHandlingLoader`\"", ",", 
                  "\"CloudObjectLoader`\"", ",", "\"PacletManager`\"", ",", 
                  "\"System`\"", ",", "\"Global`\""}], "}"}], ",", 
              System`RowBox[{"{", System`RowBox[{"\"Global`\"", ",", 
                  "\"System`\""}], "}"}]}], "]"}], ",", 
          System`RowBox[{"{", System`RowBox[{"\"System`\"", ",", 
              "\"Global`\""}], "}"}]}], "]"}]}], "]"}]], "Input", 
 System`GeneratedCell -> System`True, System`CellAutoOverwrite -> 
  System`True, System`CellChangeTimes -> {3.6816452909670954*^9}]
