System`Cell[System`BoxData[System`RowBox[{"Block", "[", 
    System`RowBox[{System`RowBox[{"{", "}"}], ",", 
      System`RowBox[{"PTest", "[", System`RowBox[
         {System`RowBox[{"HasAlphaChannel", "[", System`RowBox[
             {"Image", "[", System`RowBox[{System`RowBox[{"RawArray", "[", 
                  System`RowBox[{"\"UnsignedInteger8\"", ",", System`RowBox[
                     {"{", System`RowBox[{System`RowBox[{"{", System`RowBox[
                          {System`RowBox[{"{", System`RowBox[{"255", ",", 
                          "255", ",", "255", ",", "0"}], "}"}], ",", 
                          System`RowBox[{"{", System`RowBox[{"255", ",", 
                          "255", ",", "255", ",", "0"}], "}"}], ",", 
                          System`RowBox[{"{", System`RowBox[{"255", ",", 
                          "255", ",", "255", ",", "0"}], "}"}], ",", 
                          System`RowBox[{"{", System`RowBox[{"255", ",", 
                          "255", ",", "255", ",", "0"}], "}"}], ",", 
                          System`RowBox[{"{", System`RowBox[{"255", ",", 
                          "255", ",", "255", ",", "0"}], "}"}], ",", 
                          System`RowBox[{"{", System`RowBox[{"255", ",", 
                          "255", ",", "255", ",", "0"}], "}"}], ",", 
                          System`RowBox[{"{", System`RowBox[{"255", ",", 
                          "255", ",", "255", ",", "0"}], "}"}], ",", 
                          System`RowBox[{"{", System`RowBox[{"255", ",", 
                          "255", ",", "255", ",", "0"}], "}"}], ",", 
                          System`RowBox[{"{", System`RowBox[{"255", ",", 
                          "255", ",", "255", ",", "0"}], "}"}], ",", 
                          System`RowBox[{"{", System`RowBox[{"255", ",", 
                          "255", ",", "255", ",", "0"}], "}"}], ",", 
                          System`RowBox[{"{", System`RowBox[{"255", ",", 
                          "255", ",", "255", ",", "0"}], "}"}], ",", 
                          System`RowBox[{"{", System`RowBox[{"255", ",", 
                          "255", ",", "255", ",", "0"}], "}"}], ",", 
                          System`RowBox[{"{", System`RowBox[{"255", ",", 
                          "255", ",", "255", ",", "0"}], "}"}], ",", 
                          System`RowBox[{"{", System`RowBox[{"255", ",", 
                          "255", ",", "255", ",", "0"}], "}"}], ",", 
                          System`RowBox[{"{", System`RowBox[{"255", ",", 
                          "255", ",", "255", ",", "0"}], "}"}], ",", 
                          System`RowBox[{"{", System`RowBox[{"255", ",", 
                          "255", ",", "255", ",", "0"}], "}"}], ",", 
                          System`RowBox[{"{", System`RowBox[{"255", ",", 
                          "255", ",", "255", ",", "0"}], "}"}], ",", 
                          System`RowBox[{"{", System`RowBox[{"255", ",", 
                          "255", ",", "255", ",", "0"}], "}"}], ",", 
                          System`RowBox[{"{", System`RowBox[{"255", ",", 
                          "255", ",", "255", ",", "0"}], "}"}], ",", 
                          System`RowBox[{"{", System`RowBox[{"255", ",", 
                          "255", ",", "255", ",", "0"}], "}"}], ",", 
                          System`RowBox[{"{", System`RowBox[{"255", ",", 
                          "255", ",", "255", ",", "0"}], "}"}], ",", 
                          System`RowBox[{"{", System`RowBox[{"255", ",", 
                          "255", ",", "255", ",", "0"}], "}"}], ",", 
                          System`RowBox[{"{", System`RowBox[{"255", ",", 
                          "255", ",", "255", ",", "0"}], "}"}], ",", 
                          System`RowBox[{"{", System`RowBox[{"255", ",", 
                          "255", ",", "255", ",", "0"}], "}"}], ",", 
                          System`RowBox[{"{", System`RowBox[{"255", ",", 
                          "255", ",", "255", ",", "0"}], "}"}], ",", 
                          System`RowBox[{"{", System`RowBox[{"255", ",", 
                          "255", ",", "255", ",", "0"}], "}"}], ",", 
                          System`RowBox[{"{", System`RowBox[{"255", ",", 
                          "255", ",", "255", ",", "0"}], "}"}]}], "}"}], ",", 
                        System`RowBox[{"{", System`RowBox[{System`RowBox[
                          {"{", System`RowBox[{"255", ",", "255", ",", "255", 
                          ",", "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "0", ",", "0", ",", 
                          "255"}], "}"}]}], "}"}], ",", System`RowBox[
                         {"{", System`RowBox[{System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "0", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "0", ",", "0", ",", 
                          "255"}], "}"}]}], "}"}], ",", System`RowBox[
                         {"{", System`RowBox[{System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "0", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "0", ",", "0", ",", 
                          "255"}], "}"}]}], "}"}], ",", System`RowBox[
                         {"{", System`RowBox[{System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "0", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "0", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "0", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "0", ",", "0", ",", 
                          "255"}], "}"}]}], "}"}], ",", System`RowBox[
                         {"{", System`RowBox[{System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "0", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "0", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "0", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "0", ",", "0", ",", 
                          "255"}], "}"}]}], "}"}], ",", System`RowBox[
                         {"{", System`RowBox[{System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "0", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "0", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "0", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "0", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "0", ",", "0", ",", 
                          "255"}], "}"}]}], "}"}], ",", System`RowBox[
                         {"{", System`RowBox[{System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "0", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "0", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "0", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "0", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "0", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "0", ",", "0", ",", 
                          "255"}], "}"}]}], "}"}], ",", System`RowBox[
                         {"{", System`RowBox[{System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "0", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "0", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "0", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "0", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "0", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "0", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "0", ",", "0", ",", 
                          "255"}], "}"}]}], "}"}], ",", System`RowBox[
                         {"{", System`RowBox[{System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "0", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "0", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "0", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "0", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "0", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "0", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "0", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "0", ",", "0", ",", 
                          "255"}], "}"}]}], "}"}], ",", System`RowBox[
                         {"{", System`RowBox[{System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "0", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "0", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "0", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "0", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "0", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "0", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "0", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "0", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "0", ",", "0", ",", 
                          "255"}], "}"}]}], "}"}], ",", System`RowBox[
                         {"{", System`RowBox[{System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "0", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "0", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "0", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "0", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "0", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "0", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "0", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "0", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "0", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "0", ",", "0", ",", 
                          "255"}], "}"}]}], "}"}], ",", System`RowBox[
                         {"{", System`RowBox[{System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "0", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "0", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "0", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "0", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "0", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "0", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "0", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "0", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "0", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "0", ",", "0", ",", 
                          "255"}], "}"}]}], "}"}], ",", System`RowBox[
                         {"{", System`RowBox[{System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "0", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "0", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "0", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "0", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "0", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "0", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "0", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "0", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "0", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "0", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "0", ",", "0", ",", 
                          "255"}], "}"}]}], "}"}], ",", System`RowBox[
                         {"{", System`RowBox[{System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "0", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "0", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "0", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "0", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "0", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "0", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "0", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "0", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "0", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "0", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "0", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "0", ",", "0", ",", 
                          "255"}], "}"}]}], "}"}], ",", System`RowBox[
                         {"{", System`RowBox[{System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "255", ",", "255", ",", 
                          "0"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"0", ",", "255", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "0", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "0", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "0", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "0", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "0", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "0", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "0", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "0", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "0", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "0", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "0", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "0", ",", "0", ",", 
                          "255"}], "}"}]}], "}"}], ",", System`RowBox[
                         {"{", System`RowBox[{System`RowBox[{"{", 
                          System`RowBox[{"0", ",", "255", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"0", ",", "255", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"0", ",", "255", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"0", ",", "255", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"0", ",", "255", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"0", ",", "255", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"0", ",", "255", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"0", ",", "255", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"0", ",", "255", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"0", ",", "255", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"0", ",", "255", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"0", ",", "255", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"0", ",", "255", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"0", ",", "255", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"0", ",", "255", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "0", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "0", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "0", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "0", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "0", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "0", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "0", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "0", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "0", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "0", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "0", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "0", ",", "0", ",", 
                          "255"}], "}"}]}], "}"}], ",", System`RowBox[
                         {"{", System`RowBox[{System`RowBox[{"{", 
                          System`RowBox[{"0", ",", "255", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"0", ",", "255", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"0", ",", "255", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"0", ",", "255", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"0", ",", "255", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"0", ",", "255", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"0", ",", "255", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"0", ",", "255", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"0", ",", "255", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"0", ",", "255", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"0", ",", "255", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"0", ",", "255", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"0", ",", "255", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"0", ",", "255", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"0", ",", "255", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "0", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "0", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "0", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "0", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "0", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "0", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "0", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "0", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "0", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "0", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "0", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "0", ",", "0", ",", 
                          "255"}], "}"}]}], "}"}], ",", System`RowBox[
                         {"{", System`RowBox[{System`RowBox[{"{", 
                          System`RowBox[{"0", ",", "255", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"0", ",", "255", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"0", ",", "255", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"0", ",", "255", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"0", ",", "255", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"0", ",", "255", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"0", ",", "255", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"0", ",", "255", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"0", ",", "255", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"0", ",", "255", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"0", ",", "255", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"0", ",", "255", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"0", ",", "255", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"0", ",", "255", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"0", ",", "255", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "0", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "0", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "0", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "0", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "0", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "0", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "0", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "0", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "0", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "0", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "0", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "0", ",", "0", ",", 
                          "255"}], "}"}]}], "}"}], ",", System`RowBox[
                         {"{", System`RowBox[{System`RowBox[{"{", 
                          System`RowBox[{"0", ",", "255", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"0", ",", "255", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"0", ",", "255", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"0", ",", "255", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"0", ",", "255", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"0", ",", "255", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"0", ",", "255", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"0", ",", "255", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"0", ",", "255", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"0", ",", "255", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"0", ",", "255", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"0", ",", "255", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"0", ",", "255", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"0", ",", "255", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"0", ",", "255", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "0", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "0", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "0", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "0", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "0", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "0", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "0", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "0", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "0", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "0", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "0", ",", "0", ",", 
                          "255"}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{"255", ",", "0", ",", "0", ",", 
                          "255"}], "}"}]}], "}"}]}], "}"}]}], "]"}], ",", 
                "\"Byte\"", ",", System`RowBox[{"ColorSpace", "\[Rule]", 
                  "\"RGB\""}], ",", System`RowBox[{"Interleaving", "\[Rule]", 
                  "True"}]}], "]"}], "]"}], ",", "True", ",", 
          System`RowBox[{"{", "}"}], ",", System`RowBox[{"{", "}"}]}], 
        "]"}]}], "]"}]], "Input", System`GeneratedCell -> System`True, 
 System`CellAutoOverwrite -> System`True, System`CellChangeTimes -> 
  {3.681645298861951*^9}]
