Cell[BoxData[RowBox[{"Persist", "[", RowBox[{"\"Scene2DGet\"", ",", 
      "\[IndentingNewLine]", "\[IndentingNewLine]", 
      RowBox[{RowBox[{"NeedsDefined", "@", "\"Scene2D\""}], ";", 
        "\[IndentingNewLine]", "\[IndentingNewLine]", 
        RowBox[{"RedefinePublicFunction", "[", "\[IndentingNewLine]", 
          RowBox[{RowBox[{"Scene2DGet", "[", RowBox[{RowBox[{"s", ":", 
                  RowBox[{"Scene2D", "[", "f_FiniteMapping", "]"}]}], ",", 
                "\"l\""}], "]"}], "\[IndentingNewLine]", ",", 
            "\"Retrieve various Properties of a scene\"", 
            "\[IndentingNewLine]", ",", RowBox[{"f", "@", "\"l\""}]}], 
          "\[IndentingNewLine]", "]"}], ";", "\[IndentingNewLine]", 
        RowBox[{RowBox[{"Scene2DGet", "[", RowBox[{RowBox[{"s", ":", 
                RowBox[{"Scene2D", "[", "f_FiniteMapping", "]"}]}], ",", 
              "\"GridData\""}], "]"}], ":=", RowBox[{"f", "@", 
            "\"GridData\""}]}], ";", "\[IndentingNewLine]", 
        RowBox[{RowBox[{"Scene2DGet", "[", RowBox[{RowBox[{"s", ":", 
                RowBox[{"Scene2D", "[", "f_FiniteMapping", "]"}]}], ",", 
              RowBox[{"p", ":", RowBox[{"{", RowBox[{"_Integer", ",", 
                    "_Integer"}], "}"}]}]}], "]"}], ":=", 
          RowBox[{"GDLookup", "[", RowBox[{RowBox[{"s", "@", 
                "\"GridData\""}], ",", "p"}], "]"}]}], ";", 
        "\[IndentingNewLine]", RowBox[{RowBox[{"Scene2DGet", "[", 
            RowBox[{RowBox[{"s", ":", RowBox[{"Scene2D", "[", 
                  "f_FiniteMapping", "]"}]}], ",", "d_String"}], "]"}], ":=", 
          RowBox[{RowBox[{"f", "@", "\"GridData\""}], "~", 
            "GDSingleDatumToArray", "~", "d"}]}], ";", "\[IndentingNewLine]", 
        "\[IndentingNewLine]", RowBox[{"(*", RowBox[{"more", " ", 
            "convenient", " ", "syntax"}], "*)"}], "\[IndentingNewLine]", 
        RowBox[{RowBox[{RowBox[{"(", RowBox[{"s", ":", RowBox[{"Scene2D", 
                  "[", "__", "]"}]}], ")"}], "[", "\"Properties\"", "]"}], 
          ":=", RowBox[{"Scene2DProperties", "@", "s"}]}], ";", 
        "\[IndentingNewLine]", RowBox[
         {RowBox[{RowBox[{"(", RowBox[{"s", ":", RowBox[{"Scene2D", "[", 
                  "__", "]"}]}], ")"}], "[", "d__", "]"}], ":=", 
          RowBox[{"Scene2DGet", "[", RowBox[{"s", ",", "d"}], "]"}]}]}]}], 
    "\[IndentingNewLine]", "]"}]], "Input", 
 CellChangeTimes -> {{3.6805635175748672*^9, 3.6805635864137363*^9}, 
   {3.68056362122238*^9, 3.680563722111163*^9}, 3.6805646351319094*^9, 
   {3.6805651314662657*^9, 3.680565195006378*^9}, {3.680620717895939*^9, 
   3.6806207338158007*^9}}, CellTags -> 
  "depersistedCell7bc2cfcf-4411-41aa-aff5-d91e27739979"]
