Cell[BoxData[RowBox[{"Persist", "[", RowBox[{"\"Global`PackagePackage\"", 
      ","}], "\[IndentingNewLine]", 
    RowBox[{"(*", " ", RowBox[{RowBox[{":", "Discussion", ":", "\n", 
          RowBox[{"Demonstrates", " ", "the", " ", "development", " ", "of", 
            " ", "an", " ", "interesting", " ", RowBox[{"package", ".", "\n", 
              "\n", "The"}], " ", "focus", " ", "is", " ", "on", " ", "the", 
            " ", "methodology"}]}], ",", " ", RowBox[{"not", " ", "on", " ", 
          "the", " ", "functions", " ", RowBox[{"implemented", ".", "\n", 
            "We"}], " ", "discuss", " ", "issues", " ", "such", " ", 
          RowBox[{"as", ":", "\n", RowBox[{RowBox[{RowBox[{"-", " ", 
                  "argument"}], " ", "checking"}], "\n", "-", " ", 
              RowBox[{"logging", "/", "debug"}], "-", "print", "\n", "-", 
              " ", RowBox[{"debugging", " ", RowBox[{"(", RowBox[
                   {"breakpoints", ",", " ", RowBox[{"radio", " ", RowBox[
                       {"(", "logging", ")"}]}]}], ")"}]}], "\n", "-", " ", 
              "messages"}]}]}], ",", " ", "errors", ",", " ", 
        RowBox[{RowBox[{"failure", " ", "reporting"}], "\n", "-", " ", 
          RowBox[{"state", " ", "cleaning"}]}], ",", " ", "resetting", ",", 
        " ", RowBox[{RowBox[{"reloading", " ", "a", " ", "package", "\n", 
            " ", "Refrain", " ", "from", " ", "using", " ", "Remove", " ", 
            "on", " ", "symbols"}], " ", "-", " ", 
          RowBox[{"other", " ", "definitions", " ", "will", " ", "stop", " ", 
            "working", " ", "if", " ", "you", "\n", " ", "use", " ", 
            RowBox[{"it", ".", " ", "Plus"}], " ", "a", " ", "ClearAll", " ", 
            "symbol", " ", "is", " ", "as", " ", "good", " ", "as", " ", "a", 
            " ", "Remove", " ", "symbol", " ", "that", " ", "has", " ", 
            "been", " ", "parsed", " ", RowBox[{"again", ".", "\n", 
              RowBox[{"-", " ", "testing"}]}]}], "\n", "-", " ", 
          RowBox[{"defining", " ", "efficient", " ", "objects"}]}], ",", " ", 
        RowBox[{RowBox[{"custom", " ", "data"}], "-", "types"}], ",", " ", 
        RowBox[{"ensuring", " ", "encapsulation"}], ",", "\n", " ", 
        RowBox[{RowBox[{"overloading", " ", "built"}], "-", 
          RowBox[{"in", " ", "functionality", " ", "and", " ", "determining", 
            " ", "an", " ", "output", " ", "syntax", " ", 
            RowBox[{"(", "usability", ")"}]}], "\n", "-", " ", 
          RowBox[{"Usage", " ", "messages"}], "\n", "-", " ", 
          RowBox[{"Documentation", "\n", " ", "Use", " ", 
            "ApplicationMaker"}]}]}], "\n", "*)"}], "\n", 
    "\[IndentingNewLine]", "]"}]], "Input", 
 CellChangeTimes -> {{3.680623416625405*^9, 3.6806234199485655*^9}}, 
 CellTags -> "depersistedCell1443a3b1-a9fc-4c93-8c95-6d07002f0efc"]
