System`Cell[System`BoxData[System`RowBox[{"Persist", "[", 
    System`RowBox[{"\"TestRIFunctionParametricSelectorTests\"", ",", 
      "\[IndentingNewLine]", "\[IndentingNewLine]", 
      System`RowBox[{"Block", "[", System`RowBox[
         {System`RowBox[{"{", System`RowBox[{"makeParametricSelector", ",", 
              "mapToSelf", ",", "s0", ",", "dp", ",", "p", ",", "data", ",", 
              "pairing", ",", "s", ",", "v", ",", "f", ",", "vars", ",", 
              "ff"}], "}"}], ",", "\[IndentingNewLine]", 
          "\[IndentingNewLine]", System`RowBox[
           {System`RowBox[{System`RowBox[{"makeParametricSelector", "[", 
                System`RowBox[{"s_", ",", "p_", ",", "dataNames_", ",", 
                  System`RowBox[{"pairing_:", "list"}]}], "]"}], ":=", 
              System`RowBox[{"Module", "[", System`RowBox[{System`RowBox[
                   {"{", "sp", "}"}], ",", "\[IndentingNewLine]", 
                  System`RowBox[{System`RowBox[{"sp", "=", System`RowBox[
                       {"FMMapKeyed", "[", "\[IndentingNewLine]", 
                        System`RowBox[{System`RowBox[{System`RowBox[
                          {"RIFunctionMakeSelector", "[", System`RowBox[
                          {System`RowBox[{"FiniteMappingMakeFromRules", "@", 
                          System`RowBox[{"s", "@", "#"}]}], ",", 
                          "dataNames"}], "]"}], "&"}], ",", 
                          "\[IndentingNewLine]", "p"}], 
                        "\[IndentingNewLine]", "]"}]}], ";", 
                    "\[IndentingNewLine]", "\[IndentingNewLine]", 
                    System`RowBox[{"RIFunctionMakePaired", "[", System`RowBox[
                       {"sp", ",", "pairing"}], "]"}]}]}], 
                "\[IndentingNewLine]", "]"}]}], ";", "\[IndentingNewLine]", 
            System`RowBox[{"s0", "=", System`RowBox[{System`RowBox[
                 {"{", "\[IndentingNewLine]", System`RowBox[{System`RowBox[
                     {"IdentityRule", "@", "wsmooth"}], ",", System`RowBox[
                     {"IdentityRule", "@", "wdata"}], ",", 
                    "\[IndentingNewLine]", "\[IndentingNewLine]", 
                    System`RowBox[{System`RowBox[{"d", "[", System`RowBox[
                         {"-", "1"}], "]"}], "\[Rule]", System`RowBox[
                       {"d", "[", System`RowBox[{"#", "-", "1"}], "]"}]}], 
                    ",", "\[IndentingNewLine]", System`RowBox[{System`RowBox[
                       {"d", "[", "0", "]"}], "\[Rule]", System`RowBox[
                       {"d", "[", "#", "]"}]}], ",", "\[IndentingNewLine]", 
                    System`RowBox[{System`RowBox[{"d", "[", "1", "]"}], 
                      "\[Rule]", System`RowBox[{"d", "[", System`RowBox[
                         {"#", "+", "1"}], "]"}]}], ",", System`RowBox[
                     {"(*", System`RowBox[{"not", " ", "strictly", " ", 
                        "necessary", " ", "for", " ", "the", " ", 
                        "\"FirstDerivative\"", " ", "variant"}], "*)"}], 
                    "\[IndentingNewLine]", "\[IndentingNewLine]", 
                    System`RowBox[{System`RowBox[{"d0", "[", "0", "]"}], 
                      "\[Rule]", System`RowBox[{"d0", "[", "#", "]"}]}]}], 
                  "\[IndentingNewLine]", "}"}], "&"}]}], ";", 
            "\[IndentingNewLine]", "\[IndentingNewLine]", 
            "\[IndentingNewLine]", System`RowBox[{"dp", "=", System`RowBox[{
                "Range", "[", System`RowBox[{"1", ",", "5"}], "]"}]}], ";", 
            "\[IndentingNewLine]", System`RowBox[{"p", "=", System`RowBox[{
                "Range", "[", System`RowBox[{"2", ",", "4"}], "]"}]}], ";", 
            System`RowBox[{"(*", System`RowBox[{"subset", " ", "of", " ", 
                "dp"}], "*)"}], "\[IndentingNewLine]", System`RowBox[
             {"data", "=", System`RowBox[{"Join", "[", System`RowBox[
                 {System`RowBox[{"d", "/@", "dp"}], ",", System`RowBox[
                   {"d0", "/@", "p"}], ",", System`RowBox[{"{", System`RowBox[
                     {"wdata", ",", "wsmooth"}], "}"}]}], "]"}]}], ";", 
            "\[IndentingNewLine]", System`RowBox[{"pairing", "=", "list"}], 
            ";", System`RowBox[{"(*", System`RowBox[{"Reverse", "@*", 
                "list"}], "*)"}], "\[IndentingNewLine]", System`RowBox[
             {"s", "=", System`RowBox[{"makeParametricSelector", "[", 
                System`RowBox[{"s0", ",", "p", ",", "data"}], "]"}]}], ";", 
            "\[IndentingNewLine]", "\[IndentingNewLine]", System`RowBox[
             {System`RowBox[{"{", "\[IndentingNewLine]", System`RowBox[
                 {System`RowBox[{"{", "\[IndentingNewLine]", System`RowBox[
                     {System`RowBox[{"RIFunctionArguments", "@", "s"}], ",", 
                      "\[IndentingNewLine]", System`RowBox[
                       {"RIFunctionOutputs", "@", "s"}], ",", 
                      "\[IndentingNewLine]", System`RowBox[{System`RowBox[
                         {"RIFunctionOutputExpressionMap", "@", "s"}], "//", 
                        "FMAsRules"}], ",", "\[IndentingNewLine]", 
                      "\[IndentingNewLine]", System`RowBox[{System`RowBox[
                         {"v", "=", System`RowBox[{"RandomReal", "[", 
                          System`RowBox[{"1.", ",", System`RowBox[{"Length", 
                          "@", System`RowBox[{"RIFunctionArguments", "@", 
                          "s"}]}]}], "]"}]}], ";", "\[IndentingNewLine]", 
                        System`RowBox[{System`RowBox[{"(", System`RowBox[
                          {System`RowBox[{System`RowBox[{
                          "RIFunctionEvaluate", "[", System`RowBox[{"s", ",", 
                          System`RowBox[{"RVarvalMake", "[", System`RowBox[
                          {System`RowBox[{"RIFunctionArguments", "@", "s"}], 
                          ",", "v"}], "]"}]}], "]"}], "//", "RVVAsRules"}], 
                          "//", "Values"}], ")"}], "==", 
                          "\[IndentingNewLine]", System`RowBox[
                          {"RIFunctionEvaluateNameless", "[", System`RowBox[
                          {"s", ",", "v"}], "]"}]}]}], ",", 
                      "\[IndentingNewLine]", "\[IndentingNewLine]", 
                      System`RowBox[{System`RowBox[
                         {"RIFunctionOutputExpressionMap", "@", "s"}], "//", 
                        "FMDomainMatrix"}], ",", "\[IndentingNewLine]", 
                      System`RowBox[{"Map", "[", System`RowBox[{"Last", ",", 
                          System`RowBox[{System`RowBox[
                          {"RIFunctionOutputExpressionMap", "@", "s"}], "//", 
                          "FMDomainMatrix"}], ",", System`RowBox[{"{", "2", 
                          "}"}]}], "]"}], ",", "\[IndentingNewLine]", 
                      System`RowBox[{System`RowBox[
                         {"RIFunctionOutputExpressionMap", "@", "s"}], "//", 
                        "FMValuesMatrix"}]}], "\[IndentingNewLine]", "}"}], 
                  "\[IndentingNewLine]", ",", "\[IndentingNewLine]", 
                  System`RowBox[{"{", System`RowBox[{System`RowBox[
                       {"RIFunctionOutputs", "@", "s"}], ",", 
                      "\[IndentingNewLine]", System`RowBox[{System`RowBox[
                         {"RIFunctionEvaluate", "[", System`RowBox[{"s", ",", 
                          System`RowBox[{"RIFunctionMakeRandomArguments", 
                          "@", "s"}]}], "]"}], "//", "RVVVariables"}]}], 
                    "\[IndentingNewLine]", "}"}], "\[IndentingNewLine]", ",", 
                  "\[IndentingNewLine]", System`RowBox[{System`RowBox[
                     {"f", "=", System`RowBox[{"RIFunctionMakeFullJacobian", 
                        "[", "s", "]"}]}], ";", "\[IndentingNewLine]", 
                    System`RowBox[{System`RowBox[{"f", "//", 
                        "RIFunctionOutputExpressionMap"}], "//", 
                      "FMAsRules"}]}], "\[IndentingNewLine]", ",", 
                  "\[IndentingNewLine]", System`RowBox[{System`RowBox[
                     {"RVVValues", "@", System`RowBox[
                       {"RIFunctionEvaluateRandom", "@", "f"}]}], "//", 
                    "SparseArrayQ"}], "\[IndentingNewLine]", ",", 
                  "\[IndentingNewLine]", System`RowBox[{"(*", System`RowBox[
                     {"depends", " ", "on", " ", "the", " ", "above", " ", 
                      "test"}], "*)"}], "\[IndentingNewLine]", System`RowBox[
                   {System`RowBox[{"vars", "=", System`RowBox[{"Keys", "@", 
                        System`RowBox[{"s0", "@", "0"}]}]}], ";", 
                    "\[IndentingNewLine]", System`RowBox[{"ff", "=", 
                      System`RowBox[{"RIFunctionMakeRepeated", "[", 
                        "\[IndentingNewLine]", System`RowBox[{System`RowBox[
                          {"RIFunctionMakeFromExpressionList", "[", 
                          "\[IndentingNewLine]", System`RowBox[{System`RowBox[
                          {System`RowBox[{"{", System`RowBox[{"wsmooth", ",", 
                          "wdata"}], "}"}], "*", System`RowBox[{"{", 
                          System`RowBox[{System`RowBox[{System`RowBox[{"d", 
                          "[", "0", "]"}], "-", System`RowBox[{"d", "[", 
                          System`RowBox[{"-", "1"}], "]"}]}], ",", 
                          System`RowBox[{System`RowBox[{"d", "[", "0", "]"}], 
                          "-", System`RowBox[{"d0", "[", "0", "]"}]}]}], 
                          "}"}]}], ",", "vars"}], "\[IndentingNewLine]", 
                          "]"}], ",", "p", ",", "pairing"}], "]"}]}], ";", 
                    "\[IndentingNewLine]", System`RowBox[{"{", 
                      "\[IndentingNewLine]", System`RowBox[{System`RowBox[
                         {"RIFunctionArguments", "@", "ff"}], ",", 
                        "\[IndentingNewLine]", System`RowBox[
                         {"RIFunctionOutputs", "@", "ff"}], ",", 
                        "\[IndentingNewLine]", "\[IndentingNewLine]", 
                        System`RowBox[{"RIFunctionArguments", "@", "s"}], 
                        ",", "\[IndentingNewLine]", System`RowBox[
                         {System`RowBox[{"v", "=", System`RowBox[
                          {"RIFunctionMakeRandomArguments", "@", "s"}]}], 
                          ";", "\[IndentingNewLine]", System`RowBox[
                          {System`RowBox[{"ff", "~", 
                          "RIFunctionEvaluateNameless", "~", System`RowBox[
                          {"(", System`RowBox[{"s", "~", 
                          "RIFunctionEvaluateNameless", "~", System`RowBox[
                          {"RVVValues", "@", "v"}]}], ")"}]}], 
                          "\[IndentingNewLine]", "==", System`RowBox[
                          {"RVVValues", "[", System`RowBox[{"ff", "~", 
                          "RIFunctionEvaluate", "~", System`RowBox[{"(", 
                          System`RowBox[{"s", "~", "RIFunctionEvaluate", "~", 
                          "v"}], ")"}]}], "]"}]}]}]}], "\[IndentingNewLine]", 
                      "}"}]}]}], "\[IndentingNewLine]", "}"}], 
              "\[IndentingNewLine]", "~", "VerificationTest", "~", 
              "\[IndentingNewLine]", System`RowBox[{"{", System`RowBox[
                 {System`RowBox[{"{", System`RowBox[{System`RowBox[{"{", 
                        System`RowBox[{System`RowBox[{"d", "[", "1", "]"}], 
                          ",", System`RowBox[{"d", "[", "2", "]"}], ",", 
                          System`RowBox[{"d", "[", "3", "]"}], ",", 
                          System`RowBox[{"d", "[", "4", "]"}], ",", 
                          System`RowBox[{"d", "[", "5", "]"}], ",", 
                          System`RowBox[{"d0", "[", "2", "]"}], ",", 
                          System`RowBox[{"d0", "[", "3", "]"}], ",", 
                          System`RowBox[{"d0", "[", "4", "]"}], ",", "wdata", 
                          ",", "wsmooth"}], "}"}], ",", System`RowBox[
                       {"{", System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{"2", ",", "wsmooth"}], "]"}], ",", 
                          System`RowBox[{"list", "[", System`RowBox[{"2", 
                          ",", "wdata"}], "]"}], ",", System`RowBox[{"list", 
                          "[", System`RowBox[{"2", ",", System`RowBox[{"d", 
                          "[", System`RowBox[{"-", "1"}], "]"}]}], "]"}], 
                          ",", System`RowBox[{"list", "[", System`RowBox[
                          {"2", ",", System`RowBox[{"d", "[", "0", "]"}]}], 
                          "]"}], ",", System`RowBox[{"list", "[", 
                          System`RowBox[{"2", ",", System`RowBox[{"d", "[", 
                          "1", "]"}]}], "]"}], ",", System`RowBox[{"list", 
                          "[", System`RowBox[{"2", ",", System`RowBox[{"d0", 
                          "[", "0", "]"}]}], "]"}], ",", System`RowBox[
                          {"list", "[", System`RowBox[{"3", ",", "wsmooth"}], 
                          "]"}], ",", System`RowBox[{"list", "[", 
                          System`RowBox[{"3", ",", "wdata"}], "]"}], ",", 
                          System`RowBox[{"list", "[", System`RowBox[{"3", 
                          ",", System`RowBox[{"d", "[", System`RowBox[{"-", 
                          "1"}], "]"}]}], "]"}], ",", System`RowBox[{"list", 
                          "[", System`RowBox[{"3", ",", System`RowBox[{"d", 
                          "[", "0", "]"}]}], "]"}], ",", System`RowBox[
                          {"list", "[", System`RowBox[{"3", ",", 
                          System`RowBox[{"d", "[", "1", "]"}]}], "]"}], ",", 
                          System`RowBox[{"list", "[", System`RowBox[{"3", 
                          ",", System`RowBox[{"d0", "[", "0", "]"}]}], "]"}], 
                          ",", System`RowBox[{"list", "[", System`RowBox[
                          {"4", ",", "wsmooth"}], "]"}], ",", System`RowBox[
                          {"list", "[", System`RowBox[{"4", ",", "wdata"}], 
                          "]"}], ",", System`RowBox[{"list", "[", 
                          System`RowBox[{"4", ",", System`RowBox[{"d", "[", 
                          System`RowBox[{"-", "1"}], "]"}]}], "]"}], ",", 
                          System`RowBox[{"list", "[", System`RowBox[{"4", 
                          ",", System`RowBox[{"d", "[", "0", "]"}]}], "]"}], 
                          ",", System`RowBox[{"list", "[", System`RowBox[
                          {"4", ",", System`RowBox[{"d", "[", "1", "]"}]}], 
                          "]"}], ",", System`RowBox[{"list", "[", 
                          System`RowBox[{"4", ",", System`RowBox[{"d0", "[", 
                          "0", "]"}]}], "]"}]}], "}"}], ",", System`RowBox[
                       {"{", System`RowBox[{System`RowBox[{System`RowBox[
                          {"list", "[", System`RowBox[{"2", ",", "wsmooth"}], 
                          "]"}], "\[Rule]", "wsmooth"}], ",", System`RowBox[
                          {System`RowBox[{"list", "[", System`RowBox[{"2", 
                          ",", "wdata"}], "]"}], "\[Rule]", "wdata"}], ",", 
                          System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{"2", ",", System`RowBox[{"d", "[", 
                          System`RowBox[{"-", "1"}], "]"}]}], "]"}], 
                          "\[Rule]", System`RowBox[{"d", "[", "1", "]"}]}], 
                          ",", System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{"2", ",", System`RowBox[{"d", "[", 
                          "0", "]"}]}], "]"}], "\[Rule]", System`RowBox[
                          {"d", "[", "2", "]"}]}], ",", System`RowBox[
                          {System`RowBox[{"list", "[", System`RowBox[{"2", 
                          ",", System`RowBox[{"d", "[", "1", "]"}]}], "]"}], 
                          "\[Rule]", System`RowBox[{"d", "[", "3", "]"}]}], 
                          ",", System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{"2", ",", System`RowBox[{"d0", "[", 
                          "0", "]"}]}], "]"}], "\[Rule]", System`RowBox[
                          {"d0", "[", "2", "]"}]}], ",", System`RowBox[
                          {System`RowBox[{"list", "[", System`RowBox[{"3", 
                          ",", "wsmooth"}], "]"}], "\[Rule]", "wsmooth"}], 
                          ",", System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{"3", ",", "wdata"}], "]"}], 
                          "\[Rule]", "wdata"}], ",", System`RowBox[
                          {System`RowBox[{"list", "[", System`RowBox[{"3", 
                          ",", System`RowBox[{"d", "[", System`RowBox[{"-", 
                          "1"}], "]"}]}], "]"}], "\[Rule]", System`RowBox[
                          {"d", "[", "2", "]"}]}], ",", System`RowBox[
                          {System`RowBox[{"list", "[", System`RowBox[{"3", 
                          ",", System`RowBox[{"d", "[", "0", "]"}]}], "]"}], 
                          "\[Rule]", System`RowBox[{"d", "[", "3", "]"}]}], 
                          ",", System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{"3", ",", System`RowBox[{"d", "[", 
                          "1", "]"}]}], "]"}], "\[Rule]", System`RowBox[
                          {"d", "[", "4", "]"}]}], ",", System`RowBox[
                          {System`RowBox[{"list", "[", System`RowBox[{"3", 
                          ",", System`RowBox[{"d0", "[", "0", "]"}]}], "]"}], 
                          "\[Rule]", System`RowBox[{"d0", "[", "3", "]"}]}], 
                          ",", System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{"4", ",", "wsmooth"}], "]"}], 
                          "\[Rule]", "wsmooth"}], ",", System`RowBox[
                          {System`RowBox[{"list", "[", System`RowBox[{"4", 
                          ",", "wdata"}], "]"}], "\[Rule]", "wdata"}], ",", 
                          System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{"4", ",", System`RowBox[{"d", "[", 
                          System`RowBox[{"-", "1"}], "]"}]}], "]"}], 
                          "\[Rule]", System`RowBox[{"d", "[", "3", "]"}]}], 
                          ",", System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{"4", ",", System`RowBox[{"d", "[", 
                          "0", "]"}]}], "]"}], "\[Rule]", System`RowBox[
                          {"d", "[", "4", "]"}]}], ",", System`RowBox[
                          {System`RowBox[{"list", "[", System`RowBox[{"4", 
                          ",", System`RowBox[{"d", "[", "1", "]"}]}], "]"}], 
                          "\[Rule]", System`RowBox[{"d", "[", "5", "]"}]}], 
                          ",", System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{"4", ",", System`RowBox[{"d0", "[", 
                          "0", "]"}]}], "]"}], "\[Rule]", System`RowBox[
                          {"d0", "[", "4", "]"}]}]}], "}"}], ",", "True", 
                      ",", System`RowBox[{"{", System`RowBox[{System`RowBox[
                          {"{", System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{"2", ",", "wsmooth"}], "]"}], ",", 
                          System`RowBox[{"list", "[", System`RowBox[{"2", 
                          ",", "wdata"}], "]"}], ",", System`RowBox[{"list", 
                          "[", System`RowBox[{"2", ",", System`RowBox[{"d", 
                          "[", System`RowBox[{"-", "1"}], "]"}]}], "]"}], 
                          ",", System`RowBox[{"list", "[", System`RowBox[
                          {"2", ",", System`RowBox[{"d", "[", "0", "]"}]}], 
                          "]"}], ",", System`RowBox[{"list", "[", 
                          System`RowBox[{"2", ",", System`RowBox[{"d", "[", 
                          "1", "]"}]}], "]"}], ",", System`RowBox[{"list", 
                          "[", System`RowBox[{"2", ",", System`RowBox[{"d0", 
                          "[", "0", "]"}]}], "]"}]}], "}"}], ",", 
                          System`RowBox[{"{", System`RowBox[{System`RowBox[
                          {"list", "[", System`RowBox[{"3", ",", "wsmooth"}], 
                          "]"}], ",", System`RowBox[{"list", "[", 
                          System`RowBox[{"3", ",", "wdata"}], "]"}], ",", 
                          System`RowBox[{"list", "[", System`RowBox[{"3", 
                          ",", System`RowBox[{"d", "[", System`RowBox[{"-", 
                          "1"}], "]"}]}], "]"}], ",", System`RowBox[{"list", 
                          "[", System`RowBox[{"3", ",", System`RowBox[{"d", 
                          "[", "0", "]"}]}], "]"}], ",", System`RowBox[
                          {"list", "[", System`RowBox[{"3", ",", 
                          System`RowBox[{"d", "[", "1", "]"}]}], "]"}], ",", 
                          System`RowBox[{"list", "[", System`RowBox[{"3", 
                          ",", System`RowBox[{"d0", "[", "0", "]"}]}], 
                          "]"}]}], "}"}], ",", System`RowBox[{"{", 
                          System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{"4", ",", "wsmooth"}], "]"}], ",", 
                          System`RowBox[{"list", "[", System`RowBox[{"4", 
                          ",", "wdata"}], "]"}], ",", System`RowBox[{"list", 
                          "[", System`RowBox[{"4", ",", System`RowBox[{"d", 
                          "[", System`RowBox[{"-", "1"}], "]"}]}], "]"}], 
                          ",", System`RowBox[{"list", "[", System`RowBox[
                          {"4", ",", System`RowBox[{"d", "[", "0", "]"}]}], 
                          "]"}], ",", System`RowBox[{"list", "[", 
                          System`RowBox[{"4", ",", System`RowBox[{"d", "[", 
                          "1", "]"}]}], "]"}], ",", System`RowBox[{"list", 
                          "[", System`RowBox[{"4", ",", System`RowBox[{"d0", 
                          "[", "0", "]"}]}], "]"}]}], "}"}]}], "}"}], ",", 
                      System`RowBox[{"{", System`RowBox[{System`RowBox[
                          {"{", System`RowBox[{"wsmooth", ",", "wdata", ",", 
                          System`RowBox[{"d", "[", System`RowBox[{"-", "1"}], 
                          "]"}], ",", System`RowBox[{"d", "[", "0", "]"}], 
                          ",", System`RowBox[{"d", "[", "1", "]"}], ",", 
                          System`RowBox[{"d0", "[", "0", "]"}]}], "}"}], ",", 
                          System`RowBox[{"{", System`RowBox[{"wsmooth", ",", 
                          "wdata", ",", System`RowBox[{"d", "[", 
                          System`RowBox[{"-", "1"}], "]"}], ",", 
                          System`RowBox[{"d", "[", "0", "]"}], ",", 
                          System`RowBox[{"d", "[", "1", "]"}], ",", 
                          System`RowBox[{"d0", "[", "0", "]"}]}], "}"}], ",", 
                          System`RowBox[{"{", System`RowBox[{"wsmooth", ",", 
                          "wdata", ",", System`RowBox[{"d", "[", 
                          System`RowBox[{"-", "1"}], "]"}], ",", 
                          System`RowBox[{"d", "[", "0", "]"}], ",", 
                          System`RowBox[{"d", "[", "1", "]"}], ",", 
                          System`RowBox[{"d0", "[", "0", "]"}]}], "}"}]}], 
                        "}"}], ",", System`RowBox[{"{", System`RowBox[
                         {System`RowBox[{"{", System`RowBox[{"wsmooth", ",", 
                          "wdata", ",", System`RowBox[{"d", "[", "1", "]"}], 
                          ",", System`RowBox[{"d", "[", "2", "]"}], ",", 
                          System`RowBox[{"d", "[", "3", "]"}], ",", 
                          System`RowBox[{"d0", "[", "2", "]"}]}], "}"}], ",", 
                          System`RowBox[{"{", System`RowBox[{"wsmooth", ",", 
                          "wdata", ",", System`RowBox[{"d", "[", "2", "]"}], 
                          ",", System`RowBox[{"d", "[", "3", "]"}], ",", 
                          System`RowBox[{"d", "[", "4", "]"}], ",", 
                          System`RowBox[{"d0", "[", "3", "]"}]}], "}"}], ",", 
                          System`RowBox[{"{", System`RowBox[{"wsmooth", ",", 
                          "wdata", ",", System`RowBox[{"d", "[", "3", "]"}], 
                          ",", System`RowBox[{"d", "[", "4", "]"}], ",", 
                          System`RowBox[{"d", "[", "5", "]"}], ",", 
                          System`RowBox[{"d0", "[", "4", "]"}]}], "}"}]}], 
                        "}"}]}], "}"}], ",", System`RowBox[{"{", 
                    System`RowBox[{System`RowBox[{"{", System`RowBox[
                         {System`RowBox[{"list", "[", System`RowBox[{"2", 
                          ",", "wsmooth"}], "]"}], ",", System`RowBox[
                          {"list", "[", System`RowBox[{"2", ",", "wdata"}], 
                          "]"}], ",", System`RowBox[{"list", "[", 
                          System`RowBox[{"2", ",", System`RowBox[{"d", "[", 
                          System`RowBox[{"-", "1"}], "]"}]}], "]"}], ",", 
                          System`RowBox[{"list", "[", System`RowBox[{"2", 
                          ",", System`RowBox[{"d", "[", "0", "]"}]}], "]"}], 
                          ",", System`RowBox[{"list", "[", System`RowBox[
                          {"2", ",", System`RowBox[{"d", "[", "1", "]"}]}], 
                          "]"}], ",", System`RowBox[{"list", "[", 
                          System`RowBox[{"2", ",", System`RowBox[{"d0", "[", 
                          "0", "]"}]}], "]"}], ",", System`RowBox[{"list", 
                          "[", System`RowBox[{"3", ",", "wsmooth"}], "]"}], 
                          ",", System`RowBox[{"list", "[", System`RowBox[
                          {"3", ",", "wdata"}], "]"}], ",", System`RowBox[
                          {"list", "[", System`RowBox[{"3", ",", 
                          System`RowBox[{"d", "[", System`RowBox[{"-", "1"}], 
                          "]"}]}], "]"}], ",", System`RowBox[{"list", "[", 
                          System`RowBox[{"3", ",", System`RowBox[{"d", "[", 
                          "0", "]"}]}], "]"}], ",", System`RowBox[{"list", 
                          "[", System`RowBox[{"3", ",", System`RowBox[{"d", 
                          "[", "1", "]"}]}], "]"}], ",", System`RowBox[
                          {"list", "[", System`RowBox[{"3", ",", 
                          System`RowBox[{"d0", "[", "0", "]"}]}], "]"}], ",", 
                          System`RowBox[{"list", "[", System`RowBox[{"4", 
                          ",", "wsmooth"}], "]"}], ",", System`RowBox[
                          {"list", "[", System`RowBox[{"4", ",", "wdata"}], 
                          "]"}], ",", System`RowBox[{"list", "[", 
                          System`RowBox[{"4", ",", System`RowBox[{"d", "[", 
                          System`RowBox[{"-", "1"}], "]"}]}], "]"}], ",", 
                          System`RowBox[{"list", "[", System`RowBox[{"4", 
                          ",", System`RowBox[{"d", "[", "0", "]"}]}], "]"}], 
                          ",", System`RowBox[{"list", "[", System`RowBox[
                          {"4", ",", System`RowBox[{"d", "[", "1", "]"}]}], 
                          "]"}], ",", System`RowBox[{"list", "[", 
                          System`RowBox[{"4", ",", System`RowBox[{"d0", "[", 
                          "0", "]"}]}], "]"}]}], "}"}], ",", System`RowBox[
                       {"{", System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{"2", ",", "wsmooth"}], "]"}], ",", 
                          System`RowBox[{"list", "[", System`RowBox[{"2", 
                          ",", "wdata"}], "]"}], ",", System`RowBox[{"list", 
                          "[", System`RowBox[{"2", ",", System`RowBox[{"d", 
                          "[", System`RowBox[{"-", "1"}], "]"}]}], "]"}], 
                          ",", System`RowBox[{"list", "[", System`RowBox[
                          {"2", ",", System`RowBox[{"d", "[", "0", "]"}]}], 
                          "]"}], ",", System`RowBox[{"list", "[", 
                          System`RowBox[{"2", ",", System`RowBox[{"d", "[", 
                          "1", "]"}]}], "]"}], ",", System`RowBox[{"list", 
                          "[", System`RowBox[{"2", ",", System`RowBox[{"d0", 
                          "[", "0", "]"}]}], "]"}], ",", System`RowBox[
                          {"list", "[", System`RowBox[{"3", ",", "wsmooth"}], 
                          "]"}], ",", System`RowBox[{"list", "[", 
                          System`RowBox[{"3", ",", "wdata"}], "]"}], ",", 
                          System`RowBox[{"list", "[", System`RowBox[{"3", 
                          ",", System`RowBox[{"d", "[", System`RowBox[{"-", 
                          "1"}], "]"}]}], "]"}], ",", System`RowBox[{"list", 
                          "[", System`RowBox[{"3", ",", System`RowBox[{"d", 
                          "[", "0", "]"}]}], "]"}], ",", System`RowBox[
                          {"list", "[", System`RowBox[{"3", ",", 
                          System`RowBox[{"d", "[", "1", "]"}]}], "]"}], ",", 
                          System`RowBox[{"list", "[", System`RowBox[{"3", 
                          ",", System`RowBox[{"d0", "[", "0", "]"}]}], "]"}], 
                          ",", System`RowBox[{"list", "[", System`RowBox[
                          {"4", ",", "wsmooth"}], "]"}], ",", System`RowBox[
                          {"list", "[", System`RowBox[{"4", ",", "wdata"}], 
                          "]"}], ",", System`RowBox[{"list", "[", 
                          System`RowBox[{"4", ",", System`RowBox[{"d", "[", 
                          System`RowBox[{"-", "1"}], "]"}]}], "]"}], ",", 
                          System`RowBox[{"list", "[", System`RowBox[{"4", 
                          ",", System`RowBox[{"d", "[", "0", "]"}]}], "]"}], 
                          ",", System`RowBox[{"list", "[", System`RowBox[
                          {"4", ",", System`RowBox[{"d", "[", "1", "]"}]}], 
                          "]"}], ",", System`RowBox[{"list", "[", 
                          System`RowBox[{"4", ",", System`RowBox[{"d0", "[", 
                          "0", "]"}]}], "]"}]}], "}"}]}], "}"}], ",", 
                  System`RowBox[{"{", System`RowBox[{System`RowBox[
                       {System`RowBox[{"list", "[", System`RowBox[
                          {System`RowBox[{"list", "[", System`RowBox[{"2", 
                          ",", "wsmooth"}], "]"}], ",", System`RowBox[{"d", 
                          "[", "1", "]"}]}], "]"}], "\[Rule]", "0.`"}], ",", 
                      System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{"2", ",", "wdata"}], "]"}], ",", 
                          System`RowBox[{"d", "[", "1", "]"}]}], "]"}], 
                        "\[Rule]", "0.`"}], ",", System`RowBox[{System`RowBox[
                         {"list", "[", System`RowBox[{System`RowBox[{"list", 
                          "[", System`RowBox[{"2", ",", System`RowBox[{"d", 
                          "[", System`RowBox[{"-", "1"}], "]"}]}], "]"}], 
                          ",", System`RowBox[{"d", "[", "1", "]"}]}], "]"}], 
                        "\[Rule]", "1.`"}], ",", System`RowBox[{System`RowBox[
                         {"list", "[", System`RowBox[{System`RowBox[{"list", 
                          "[", System`RowBox[{"2", ",", System`RowBox[{"d", 
                          "[", "0", "]"}]}], "]"}], ",", System`RowBox[
                          {"d", "[", "1", "]"}]}], "]"}], "\[Rule]", "0.`"}], 
                      ",", System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{"2", ",", System`RowBox[{"d", "[", 
                          "1", "]"}]}], "]"}], ",", System`RowBox[{"d", "[", 
                          "1", "]"}]}], "]"}], "\[Rule]", "0.`"}], ",", 
                      System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{"2", ",", System`RowBox[{"d0", "[", 
                          "0", "]"}]}], "]"}], ",", System`RowBox[{"d", "[", 
                          "1", "]"}]}], "]"}], "\[Rule]", "0.`"}], ",", 
                      System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{"3", ",", "wsmooth"}], "]"}], ",", 
                          System`RowBox[{"d", "[", "1", "]"}]}], "]"}], 
                        "\[Rule]", "0.`"}], ",", System`RowBox[{System`RowBox[
                         {"list", "[", System`RowBox[{System`RowBox[{"list", 
                          "[", System`RowBox[{"3", ",", "wdata"}], "]"}], 
                          ",", System`RowBox[{"d", "[", "1", "]"}]}], "]"}], 
                        "\[Rule]", "0.`"}], ",", System`RowBox[{System`RowBox[
                         {"list", "[", System`RowBox[{System`RowBox[{"list", 
                          "[", System`RowBox[{"3", ",", System`RowBox[{"d", 
                          "[", System`RowBox[{"-", "1"}], "]"}]}], "]"}], 
                          ",", System`RowBox[{"d", "[", "1", "]"}]}], "]"}], 
                        "\[Rule]", "0.`"}], ",", System`RowBox[{System`RowBox[
                         {"list", "[", System`RowBox[{System`RowBox[{"list", 
                          "[", System`RowBox[{"3", ",", System`RowBox[{"d", 
                          "[", "0", "]"}]}], "]"}], ",", System`RowBox[
                          {"d", "[", "1", "]"}]}], "]"}], "\[Rule]", "0.`"}], 
                      ",", System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{"3", ",", System`RowBox[{"d", "[", 
                          "1", "]"}]}], "]"}], ",", System`RowBox[{"d", "[", 
                          "1", "]"}]}], "]"}], "\[Rule]", "0.`"}], ",", 
                      System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{"3", ",", System`RowBox[{"d0", "[", 
                          "0", "]"}]}], "]"}], ",", System`RowBox[{"d", "[", 
                          "1", "]"}]}], "]"}], "\[Rule]", "0.`"}], ",", 
                      System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{"4", ",", "wsmooth"}], "]"}], ",", 
                          System`RowBox[{"d", "[", "1", "]"}]}], "]"}], 
                        "\[Rule]", "0.`"}], ",", System`RowBox[{System`RowBox[
                         {"list", "[", System`RowBox[{System`RowBox[{"list", 
                          "[", System`RowBox[{"4", ",", "wdata"}], "]"}], 
                          ",", System`RowBox[{"d", "[", "1", "]"}]}], "]"}], 
                        "\[Rule]", "0.`"}], ",", System`RowBox[{System`RowBox[
                         {"list", "[", System`RowBox[{System`RowBox[{"list", 
                          "[", System`RowBox[{"4", ",", System`RowBox[{"d", 
                          "[", System`RowBox[{"-", "1"}], "]"}]}], "]"}], 
                          ",", System`RowBox[{"d", "[", "1", "]"}]}], "]"}], 
                        "\[Rule]", "0.`"}], ",", System`RowBox[{System`RowBox[
                         {"list", "[", System`RowBox[{System`RowBox[{"list", 
                          "[", System`RowBox[{"4", ",", System`RowBox[{"d", 
                          "[", "0", "]"}]}], "]"}], ",", System`RowBox[
                          {"d", "[", "1", "]"}]}], "]"}], "\[Rule]", "0.`"}], 
                      ",", System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{"4", ",", System`RowBox[{"d", "[", 
                          "1", "]"}]}], "]"}], ",", System`RowBox[{"d", "[", 
                          "1", "]"}]}], "]"}], "\[Rule]", "0.`"}], ",", 
                      System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{"4", ",", System`RowBox[{"d0", "[", 
                          "0", "]"}]}], "]"}], ",", System`RowBox[{"d", "[", 
                          "1", "]"}]}], "]"}], "\[Rule]", "0.`"}], ",", 
                      System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{"2", ",", "wsmooth"}], "]"}], ",", 
                          System`RowBox[{"d", "[", "2", "]"}]}], "]"}], 
                        "\[Rule]", "0.`"}], ",", System`RowBox[{System`RowBox[
                         {"list", "[", System`RowBox[{System`RowBox[{"list", 
                          "[", System`RowBox[{"2", ",", "wdata"}], "]"}], 
                          ",", System`RowBox[{"d", "[", "2", "]"}]}], "]"}], 
                        "\[Rule]", "0.`"}], ",", System`RowBox[{System`RowBox[
                         {"list", "[", System`RowBox[{System`RowBox[{"list", 
                          "[", System`RowBox[{"2", ",", System`RowBox[{"d", 
                          "[", System`RowBox[{"-", "1"}], "]"}]}], "]"}], 
                          ",", System`RowBox[{"d", "[", "2", "]"}]}], "]"}], 
                        "\[Rule]", "0.`"}], ",", System`RowBox[{System`RowBox[
                         {"list", "[", System`RowBox[{System`RowBox[{"list", 
                          "[", System`RowBox[{"2", ",", System`RowBox[{"d", 
                          "[", "0", "]"}]}], "]"}], ",", System`RowBox[
                          {"d", "[", "2", "]"}]}], "]"}], "\[Rule]", "1.`"}], 
                      ",", System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{"2", ",", System`RowBox[{"d", "[", 
                          "1", "]"}]}], "]"}], ",", System`RowBox[{"d", "[", 
                          "2", "]"}]}], "]"}], "\[Rule]", "0.`"}], ",", 
                      System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{"2", ",", System`RowBox[{"d0", "[", 
                          "0", "]"}]}], "]"}], ",", System`RowBox[{"d", "[", 
                          "2", "]"}]}], "]"}], "\[Rule]", "0.`"}], ",", 
                      System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{"3", ",", "wsmooth"}], "]"}], ",", 
                          System`RowBox[{"d", "[", "2", "]"}]}], "]"}], 
                        "\[Rule]", "0.`"}], ",", System`RowBox[{System`RowBox[
                         {"list", "[", System`RowBox[{System`RowBox[{"list", 
                          "[", System`RowBox[{"3", ",", "wdata"}], "]"}], 
                          ",", System`RowBox[{"d", "[", "2", "]"}]}], "]"}], 
                        "\[Rule]", "0.`"}], ",", System`RowBox[{System`RowBox[
                         {"list", "[", System`RowBox[{System`RowBox[{"list", 
                          "[", System`RowBox[{"3", ",", System`RowBox[{"d", 
                          "[", System`RowBox[{"-", "1"}], "]"}]}], "]"}], 
                          ",", System`RowBox[{"d", "[", "2", "]"}]}], "]"}], 
                        "\[Rule]", "1.`"}], ",", System`RowBox[{System`RowBox[
                         {"list", "[", System`RowBox[{System`RowBox[{"list", 
                          "[", System`RowBox[{"3", ",", System`RowBox[{"d", 
                          "[", "0", "]"}]}], "]"}], ",", System`RowBox[
                          {"d", "[", "2", "]"}]}], "]"}], "\[Rule]", "0.`"}], 
                      ",", System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{"3", ",", System`RowBox[{"d", "[", 
                          "1", "]"}]}], "]"}], ",", System`RowBox[{"d", "[", 
                          "2", "]"}]}], "]"}], "\[Rule]", "0.`"}], ",", 
                      System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{"3", ",", System`RowBox[{"d0", "[", 
                          "0", "]"}]}], "]"}], ",", System`RowBox[{"d", "[", 
                          "2", "]"}]}], "]"}], "\[Rule]", "0.`"}], ",", 
                      System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{"4", ",", "wsmooth"}], "]"}], ",", 
                          System`RowBox[{"d", "[", "2", "]"}]}], "]"}], 
                        "\[Rule]", "0.`"}], ",", System`RowBox[{System`RowBox[
                         {"list", "[", System`RowBox[{System`RowBox[{"list", 
                          "[", System`RowBox[{"4", ",", "wdata"}], "]"}], 
                          ",", System`RowBox[{"d", "[", "2", "]"}]}], "]"}], 
                        "\[Rule]", "0.`"}], ",", System`RowBox[{System`RowBox[
                         {"list", "[", System`RowBox[{System`RowBox[{"list", 
                          "[", System`RowBox[{"4", ",", System`RowBox[{"d", 
                          "[", System`RowBox[{"-", "1"}], "]"}]}], "]"}], 
                          ",", System`RowBox[{"d", "[", "2", "]"}]}], "]"}], 
                        "\[Rule]", "0.`"}], ",", System`RowBox[{System`RowBox[
                         {"list", "[", System`RowBox[{System`RowBox[{"list", 
                          "[", System`RowBox[{"4", ",", System`RowBox[{"d", 
                          "[", "0", "]"}]}], "]"}], ",", System`RowBox[
                          {"d", "[", "2", "]"}]}], "]"}], "\[Rule]", "0.`"}], 
                      ",", System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{"4", ",", System`RowBox[{"d", "[", 
                          "1", "]"}]}], "]"}], ",", System`RowBox[{"d", "[", 
                          "2", "]"}]}], "]"}], "\[Rule]", "0.`"}], ",", 
                      System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{"4", ",", System`RowBox[{"d0", "[", 
                          "0", "]"}]}], "]"}], ",", System`RowBox[{"d", "[", 
                          "2", "]"}]}], "]"}], "\[Rule]", "0.`"}], ",", 
                      System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{"2", ",", "wsmooth"}], "]"}], ",", 
                          System`RowBox[{"d", "[", "3", "]"}]}], "]"}], 
                        "\[Rule]", "0.`"}], ",", System`RowBox[{System`RowBox[
                         {"list", "[", System`RowBox[{System`RowBox[{"list", 
                          "[", System`RowBox[{"2", ",", "wdata"}], "]"}], 
                          ",", System`RowBox[{"d", "[", "3", "]"}]}], "]"}], 
                        "\[Rule]", "0.`"}], ",", System`RowBox[{System`RowBox[
                         {"list", "[", System`RowBox[{System`RowBox[{"list", 
                          "[", System`RowBox[{"2", ",", System`RowBox[{"d", 
                          "[", System`RowBox[{"-", "1"}], "]"}]}], "]"}], 
                          ",", System`RowBox[{"d", "[", "3", "]"}]}], "]"}], 
                        "\[Rule]", "0.`"}], ",", System`RowBox[{System`RowBox[
                         {"list", "[", System`RowBox[{System`RowBox[{"list", 
                          "[", System`RowBox[{"2", ",", System`RowBox[{"d", 
                          "[", "0", "]"}]}], "]"}], ",", System`RowBox[
                          {"d", "[", "3", "]"}]}], "]"}], "\[Rule]", "0.`"}], 
                      ",", System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{"2", ",", System`RowBox[{"d", "[", 
                          "1", "]"}]}], "]"}], ",", System`RowBox[{"d", "[", 
                          "3", "]"}]}], "]"}], "\[Rule]", "1.`"}], ",", 
                      System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{"2", ",", System`RowBox[{"d0", "[", 
                          "0", "]"}]}], "]"}], ",", System`RowBox[{"d", "[", 
                          "3", "]"}]}], "]"}], "\[Rule]", "0.`"}], ",", 
                      System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{"3", ",", "wsmooth"}], "]"}], ",", 
                          System`RowBox[{"d", "[", "3", "]"}]}], "]"}], 
                        "\[Rule]", "0.`"}], ",", System`RowBox[{System`RowBox[
                         {"list", "[", System`RowBox[{System`RowBox[{"list", 
                          "[", System`RowBox[{"3", ",", "wdata"}], "]"}], 
                          ",", System`RowBox[{"d", "[", "3", "]"}]}], "]"}], 
                        "\[Rule]", "0.`"}], ",", System`RowBox[{System`RowBox[
                         {"list", "[", System`RowBox[{System`RowBox[{"list", 
                          "[", System`RowBox[{"3", ",", System`RowBox[{"d", 
                          "[", System`RowBox[{"-", "1"}], "]"}]}], "]"}], 
                          ",", System`RowBox[{"d", "[", "3", "]"}]}], "]"}], 
                        "\[Rule]", "0.`"}], ",", System`RowBox[{System`RowBox[
                         {"list", "[", System`RowBox[{System`RowBox[{"list", 
                          "[", System`RowBox[{"3", ",", System`RowBox[{"d", 
                          "[", "0", "]"}]}], "]"}], ",", System`RowBox[
                          {"d", "[", "3", "]"}]}], "]"}], "\[Rule]", "1.`"}], 
                      ",", System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{"3", ",", System`RowBox[{"d", "[", 
                          "1", "]"}]}], "]"}], ",", System`RowBox[{"d", "[", 
                          "3", "]"}]}], "]"}], "\[Rule]", "0.`"}], ",", 
                      System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{"3", ",", System`RowBox[{"d0", "[", 
                          "0", "]"}]}], "]"}], ",", System`RowBox[{"d", "[", 
                          "3", "]"}]}], "]"}], "\[Rule]", "0.`"}], ",", 
                      System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{"4", ",", "wsmooth"}], "]"}], ",", 
                          System`RowBox[{"d", "[", "3", "]"}]}], "]"}], 
                        "\[Rule]", "0.`"}], ",", System`RowBox[{System`RowBox[
                         {"list", "[", System`RowBox[{System`RowBox[{"list", 
                          "[", System`RowBox[{"4", ",", "wdata"}], "]"}], 
                          ",", System`RowBox[{"d", "[", "3", "]"}]}], "]"}], 
                        "\[Rule]", "0.`"}], ",", System`RowBox[{System`RowBox[
                         {"list", "[", System`RowBox[{System`RowBox[{"list", 
                          "[", System`RowBox[{"4", ",", System`RowBox[{"d", 
                          "[", System`RowBox[{"-", "1"}], "]"}]}], "]"}], 
                          ",", System`RowBox[{"d", "[", "3", "]"}]}], "]"}], 
                        "\[Rule]", "1.`"}], ",", System`RowBox[{System`RowBox[
                         {"list", "[", System`RowBox[{System`RowBox[{"list", 
                          "[", System`RowBox[{"4", ",", System`RowBox[{"d", 
                          "[", "0", "]"}]}], "]"}], ",", System`RowBox[
                          {"d", "[", "3", "]"}]}], "]"}], "\[Rule]", "0.`"}], 
                      ",", System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{"4", ",", System`RowBox[{"d", "[", 
                          "1", "]"}]}], "]"}], ",", System`RowBox[{"d", "[", 
                          "3", "]"}]}], "]"}], "\[Rule]", "0.`"}], ",", 
                      System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{"4", ",", System`RowBox[{"d0", "[", 
                          "0", "]"}]}], "]"}], ",", System`RowBox[{"d", "[", 
                          "3", "]"}]}], "]"}], "\[Rule]", "0.`"}], ",", 
                      System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{"2", ",", "wsmooth"}], "]"}], ",", 
                          System`RowBox[{"d", "[", "4", "]"}]}], "]"}], 
                        "\[Rule]", "0.`"}], ",", System`RowBox[{System`RowBox[
                         {"list", "[", System`RowBox[{System`RowBox[{"list", 
                          "[", System`RowBox[{"2", ",", "wdata"}], "]"}], 
                          ",", System`RowBox[{"d", "[", "4", "]"}]}], "]"}], 
                        "\[Rule]", "0.`"}], ",", System`RowBox[{System`RowBox[
                         {"list", "[", System`RowBox[{System`RowBox[{"list", 
                          "[", System`RowBox[{"2", ",", System`RowBox[{"d", 
                          "[", System`RowBox[{"-", "1"}], "]"}]}], "]"}], 
                          ",", System`RowBox[{"d", "[", "4", "]"}]}], "]"}], 
                        "\[Rule]", "0.`"}], ",", System`RowBox[{System`RowBox[
                         {"list", "[", System`RowBox[{System`RowBox[{"list", 
                          "[", System`RowBox[{"2", ",", System`RowBox[{"d", 
                          "[", "0", "]"}]}], "]"}], ",", System`RowBox[
                          {"d", "[", "4", "]"}]}], "]"}], "\[Rule]", "0.`"}], 
                      ",", System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{"2", ",", System`RowBox[{"d", "[", 
                          "1", "]"}]}], "]"}], ",", System`RowBox[{"d", "[", 
                          "4", "]"}]}], "]"}], "\[Rule]", "0.`"}], ",", 
                      System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{"2", ",", System`RowBox[{"d0", "[", 
                          "0", "]"}]}], "]"}], ",", System`RowBox[{"d", "[", 
                          "4", "]"}]}], "]"}], "\[Rule]", "0.`"}], ",", 
                      System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{"3", ",", "wsmooth"}], "]"}], ",", 
                          System`RowBox[{"d", "[", "4", "]"}]}], "]"}], 
                        "\[Rule]", "0.`"}], ",", System`RowBox[{System`RowBox[
                         {"list", "[", System`RowBox[{System`RowBox[{"list", 
                          "[", System`RowBox[{"3", ",", "wdata"}], "]"}], 
                          ",", System`RowBox[{"d", "[", "4", "]"}]}], "]"}], 
                        "\[Rule]", "0.`"}], ",", System`RowBox[{System`RowBox[
                         {"list", "[", System`RowBox[{System`RowBox[{"list", 
                          "[", System`RowBox[{"3", ",", System`RowBox[{"d", 
                          "[", System`RowBox[{"-", "1"}], "]"}]}], "]"}], 
                          ",", System`RowBox[{"d", "[", "4", "]"}]}], "]"}], 
                        "\[Rule]", "0.`"}], ",", System`RowBox[{System`RowBox[
                         {"list", "[", System`RowBox[{System`RowBox[{"list", 
                          "[", System`RowBox[{"3", ",", System`RowBox[{"d", 
                          "[", "0", "]"}]}], "]"}], ",", System`RowBox[
                          {"d", "[", "4", "]"}]}], "]"}], "\[Rule]", "0.`"}], 
                      ",", System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{"3", ",", System`RowBox[{"d", "[", 
                          "1", "]"}]}], "]"}], ",", System`RowBox[{"d", "[", 
                          "4", "]"}]}], "]"}], "\[Rule]", "1.`"}], ",", 
                      System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{"3", ",", System`RowBox[{"d0", "[", 
                          "0", "]"}]}], "]"}], ",", System`RowBox[{"d", "[", 
                          "4", "]"}]}], "]"}], "\[Rule]", "0.`"}], ",", 
                      System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{"4", ",", "wsmooth"}], "]"}], ",", 
                          System`RowBox[{"d", "[", "4", "]"}]}], "]"}], 
                        "\[Rule]", "0.`"}], ",", System`RowBox[{System`RowBox[
                         {"list", "[", System`RowBox[{System`RowBox[{"list", 
                          "[", System`RowBox[{"4", ",", "wdata"}], "]"}], 
                          ",", System`RowBox[{"d", "[", "4", "]"}]}], "]"}], 
                        "\[Rule]", "0.`"}], ",", System`RowBox[{System`RowBox[
                         {"list", "[", System`RowBox[{System`RowBox[{"list", 
                          "[", System`RowBox[{"4", ",", System`RowBox[{"d", 
                          "[", System`RowBox[{"-", "1"}], "]"}]}], "]"}], 
                          ",", System`RowBox[{"d", "[", "4", "]"}]}], "]"}], 
                        "\[Rule]", "0.`"}], ",", System`RowBox[{System`RowBox[
                         {"list", "[", System`RowBox[{System`RowBox[{"list", 
                          "[", System`RowBox[{"4", ",", System`RowBox[{"d", 
                          "[", "0", "]"}]}], "]"}], ",", System`RowBox[
                          {"d", "[", "4", "]"}]}], "]"}], "\[Rule]", "1.`"}], 
                      ",", System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{"4", ",", System`RowBox[{"d", "[", 
                          "1", "]"}]}], "]"}], ",", System`RowBox[{"d", "[", 
                          "4", "]"}]}], "]"}], "\[Rule]", "0.`"}], ",", 
                      System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{"4", ",", System`RowBox[{"d0", "[", 
                          "0", "]"}]}], "]"}], ",", System`RowBox[{"d", "[", 
                          "4", "]"}]}], "]"}], "\[Rule]", "0.`"}], ",", 
                      System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{"2", ",", "wsmooth"}], "]"}], ",", 
                          System`RowBox[{"d", "[", "5", "]"}]}], "]"}], 
                        "\[Rule]", "0.`"}], ",", System`RowBox[{System`RowBox[
                         {"list", "[", System`RowBox[{System`RowBox[{"list", 
                          "[", System`RowBox[{"2", ",", "wdata"}], "]"}], 
                          ",", System`RowBox[{"d", "[", "5", "]"}]}], "]"}], 
                        "\[Rule]", "0.`"}], ",", System`RowBox[{System`RowBox[
                         {"list", "[", System`RowBox[{System`RowBox[{"list", 
                          "[", System`RowBox[{"2", ",", System`RowBox[{"d", 
                          "[", System`RowBox[{"-", "1"}], "]"}]}], "]"}], 
                          ",", System`RowBox[{"d", "[", "5", "]"}]}], "]"}], 
                        "\[Rule]", "0.`"}], ",", System`RowBox[{System`RowBox[
                         {"list", "[", System`RowBox[{System`RowBox[{"list", 
                          "[", System`RowBox[{"2", ",", System`RowBox[{"d", 
                          "[", "0", "]"}]}], "]"}], ",", System`RowBox[
                          {"d", "[", "5", "]"}]}], "]"}], "\[Rule]", "0.`"}], 
                      ",", System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{"2", ",", System`RowBox[{"d", "[", 
                          "1", "]"}]}], "]"}], ",", System`RowBox[{"d", "[", 
                          "5", "]"}]}], "]"}], "\[Rule]", "0.`"}], ",", 
                      System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{"2", ",", System`RowBox[{"d0", "[", 
                          "0", "]"}]}], "]"}], ",", System`RowBox[{"d", "[", 
                          "5", "]"}]}], "]"}], "\[Rule]", "0.`"}], ",", 
                      System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{"3", ",", "wsmooth"}], "]"}], ",", 
                          System`RowBox[{"d", "[", "5", "]"}]}], "]"}], 
                        "\[Rule]", "0.`"}], ",", System`RowBox[{System`RowBox[
                         {"list", "[", System`RowBox[{System`RowBox[{"list", 
                          "[", System`RowBox[{"3", ",", "wdata"}], "]"}], 
                          ",", System`RowBox[{"d", "[", "5", "]"}]}], "]"}], 
                        "\[Rule]", "0.`"}], ",", System`RowBox[{System`RowBox[
                         {"list", "[", System`RowBox[{System`RowBox[{"list", 
                          "[", System`RowBox[{"3", ",", System`RowBox[{"d", 
                          "[", System`RowBox[{"-", "1"}], "]"}]}], "]"}], 
                          ",", System`RowBox[{"d", "[", "5", "]"}]}], "]"}], 
                        "\[Rule]", "0.`"}], ",", System`RowBox[{System`RowBox[
                         {"list", "[", System`RowBox[{System`RowBox[{"list", 
                          "[", System`RowBox[{"3", ",", System`RowBox[{"d", 
                          "[", "0", "]"}]}], "]"}], ",", System`RowBox[
                          {"d", "[", "5", "]"}]}], "]"}], "\[Rule]", "0.`"}], 
                      ",", System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{"3", ",", System`RowBox[{"d", "[", 
                          "1", "]"}]}], "]"}], ",", System`RowBox[{"d", "[", 
                          "5", "]"}]}], "]"}], "\[Rule]", "0.`"}], ",", 
                      System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{"3", ",", System`RowBox[{"d0", "[", 
                          "0", "]"}]}], "]"}], ",", System`RowBox[{"d", "[", 
                          "5", "]"}]}], "]"}], "\[Rule]", "0.`"}], ",", 
                      System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{"4", ",", "wsmooth"}], "]"}], ",", 
                          System`RowBox[{"d", "[", "5", "]"}]}], "]"}], 
                        "\[Rule]", "0.`"}], ",", System`RowBox[{System`RowBox[
                         {"list", "[", System`RowBox[{System`RowBox[{"list", 
                          "[", System`RowBox[{"4", ",", "wdata"}], "]"}], 
                          ",", System`RowBox[{"d", "[", "5", "]"}]}], "]"}], 
                        "\[Rule]", "0.`"}], ",", System`RowBox[{System`RowBox[
                         {"list", "[", System`RowBox[{System`RowBox[{"list", 
                          "[", System`RowBox[{"4", ",", System`RowBox[{"d", 
                          "[", System`RowBox[{"-", "1"}], "]"}]}], "]"}], 
                          ",", System`RowBox[{"d", "[", "5", "]"}]}], "]"}], 
                        "\[Rule]", "0.`"}], ",", System`RowBox[{System`RowBox[
                         {"list", "[", System`RowBox[{System`RowBox[{"list", 
                          "[", System`RowBox[{"4", ",", System`RowBox[{"d", 
                          "[", "0", "]"}]}], "]"}], ",", System`RowBox[
                          {"d", "[", "5", "]"}]}], "]"}], "\[Rule]", "0.`"}], 
                      ",", System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{"4", ",", System`RowBox[{"d", "[", 
                          "1", "]"}]}], "]"}], ",", System`RowBox[{"d", "[", 
                          "5", "]"}]}], "]"}], "\[Rule]", "1.`"}], ",", 
                      System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{"4", ",", System`RowBox[{"d0", "[", 
                          "0", "]"}]}], "]"}], ",", System`RowBox[{"d", "[", 
                          "5", "]"}]}], "]"}], "\[Rule]", "0.`"}], ",", 
                      System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{"2", ",", "wsmooth"}], "]"}], ",", 
                          System`RowBox[{"d0", "[", "2", "]"}]}], "]"}], 
                        "\[Rule]", "0.`"}], ",", System`RowBox[{System`RowBox[
                         {"list", "[", System`RowBox[{System`RowBox[{"list", 
                          "[", System`RowBox[{"2", ",", "wdata"}], "]"}], 
                          ",", System`RowBox[{"d0", "[", "2", "]"}]}], "]"}], 
                        "\[Rule]", "0.`"}], ",", System`RowBox[{System`RowBox[
                         {"list", "[", System`RowBox[{System`RowBox[{"list", 
                          "[", System`RowBox[{"2", ",", System`RowBox[{"d", 
                          "[", System`RowBox[{"-", "1"}], "]"}]}], "]"}], 
                          ",", System`RowBox[{"d0", "[", "2", "]"}]}], "]"}], 
                        "\[Rule]", "0.`"}], ",", System`RowBox[{System`RowBox[
                         {"list", "[", System`RowBox[{System`RowBox[{"list", 
                          "[", System`RowBox[{"2", ",", System`RowBox[{"d", 
                          "[", "0", "]"}]}], "]"}], ",", System`RowBox[
                          {"d0", "[", "2", "]"}]}], "]"}], "\[Rule]", 
                        "0.`"}], ",", System`RowBox[{System`RowBox[{"list", 
                          "[", System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{"2", ",", System`RowBox[{"d", "[", 
                          "1", "]"}]}], "]"}], ",", System`RowBox[{"d0", "[", 
                          "2", "]"}]}], "]"}], "\[Rule]", "0.`"}], ",", 
                      System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{"2", ",", System`RowBox[{"d0", "[", 
                          "0", "]"}]}], "]"}], ",", System`RowBox[{"d0", "[", 
                          "2", "]"}]}], "]"}], "\[Rule]", "1.`"}], ",", 
                      System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{"3", ",", "wsmooth"}], "]"}], ",", 
                          System`RowBox[{"d0", "[", "2", "]"}]}], "]"}], 
                        "\[Rule]", "0.`"}], ",", System`RowBox[{System`RowBox[
                         {"list", "[", System`RowBox[{System`RowBox[{"list", 
                          "[", System`RowBox[{"3", ",", "wdata"}], "]"}], 
                          ",", System`RowBox[{"d0", "[", "2", "]"}]}], "]"}], 
                        "\[Rule]", "0.`"}], ",", System`RowBox[{System`RowBox[
                         {"list", "[", System`RowBox[{System`RowBox[{"list", 
                          "[", System`RowBox[{"3", ",", System`RowBox[{"d", 
                          "[", System`RowBox[{"-", "1"}], "]"}]}], "]"}], 
                          ",", System`RowBox[{"d0", "[", "2", "]"}]}], "]"}], 
                        "\[Rule]", "0.`"}], ",", System`RowBox[{System`RowBox[
                         {"list", "[", System`RowBox[{System`RowBox[{"list", 
                          "[", System`RowBox[{"3", ",", System`RowBox[{"d", 
                          "[", "0", "]"}]}], "]"}], ",", System`RowBox[
                          {"d0", "[", "2", "]"}]}], "]"}], "\[Rule]", 
                        "0.`"}], ",", System`RowBox[{System`RowBox[{"list", 
                          "[", System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{"3", ",", System`RowBox[{"d", "[", 
                          "1", "]"}]}], "]"}], ",", System`RowBox[{"d0", "[", 
                          "2", "]"}]}], "]"}], "\[Rule]", "0.`"}], ",", 
                      System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{"3", ",", System`RowBox[{"d0", "[", 
                          "0", "]"}]}], "]"}], ",", System`RowBox[{"d0", "[", 
                          "2", "]"}]}], "]"}], "\[Rule]", "0.`"}], ",", 
                      System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{"4", ",", "wsmooth"}], "]"}], ",", 
                          System`RowBox[{"d0", "[", "2", "]"}]}], "]"}], 
                        "\[Rule]", "0.`"}], ",", System`RowBox[{System`RowBox[
                         {"list", "[", System`RowBox[{System`RowBox[{"list", 
                          "[", System`RowBox[{"4", ",", "wdata"}], "]"}], 
                          ",", System`RowBox[{"d0", "[", "2", "]"}]}], "]"}], 
                        "\[Rule]", "0.`"}], ",", System`RowBox[{System`RowBox[
                         {"list", "[", System`RowBox[{System`RowBox[{"list", 
                          "[", System`RowBox[{"4", ",", System`RowBox[{"d", 
                          "[", System`RowBox[{"-", "1"}], "]"}]}], "]"}], 
                          ",", System`RowBox[{"d0", "[", "2", "]"}]}], "]"}], 
                        "\[Rule]", "0.`"}], ",", System`RowBox[{System`RowBox[
                         {"list", "[", System`RowBox[{System`RowBox[{"list", 
                          "[", System`RowBox[{"4", ",", System`RowBox[{"d", 
                          "[", "0", "]"}]}], "]"}], ",", System`RowBox[
                          {"d0", "[", "2", "]"}]}], "]"}], "\[Rule]", 
                        "0.`"}], ",", System`RowBox[{System`RowBox[{"list", 
                          "[", System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{"4", ",", System`RowBox[{"d", "[", 
                          "1", "]"}]}], "]"}], ",", System`RowBox[{"d0", "[", 
                          "2", "]"}]}], "]"}], "\[Rule]", "0.`"}], ",", 
                      System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{"4", ",", System`RowBox[{"d0", "[", 
                          "0", "]"}]}], "]"}], ",", System`RowBox[{"d0", "[", 
                          "2", "]"}]}], "]"}], "\[Rule]", "0.`"}], ",", 
                      System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{"2", ",", "wsmooth"}], "]"}], ",", 
                          System`RowBox[{"d0", "[", "3", "]"}]}], "]"}], 
                        "\[Rule]", "0.`"}], ",", System`RowBox[{System`RowBox[
                         {"list", "[", System`RowBox[{System`RowBox[{"list", 
                          "[", System`RowBox[{"2", ",", "wdata"}], "]"}], 
                          ",", System`RowBox[{"d0", "[", "3", "]"}]}], "]"}], 
                        "\[Rule]", "0.`"}], ",", System`RowBox[{System`RowBox[
                         {"list", "[", System`RowBox[{System`RowBox[{"list", 
                          "[", System`RowBox[{"2", ",", System`RowBox[{"d", 
                          "[", System`RowBox[{"-", "1"}], "]"}]}], "]"}], 
                          ",", System`RowBox[{"d0", "[", "3", "]"}]}], "]"}], 
                        "\[Rule]", "0.`"}], ",", System`RowBox[{System`RowBox[
                         {"list", "[", System`RowBox[{System`RowBox[{"list", 
                          "[", System`RowBox[{"2", ",", System`RowBox[{"d", 
                          "[", "0", "]"}]}], "]"}], ",", System`RowBox[
                          {"d0", "[", "3", "]"}]}], "]"}], "\[Rule]", 
                        "0.`"}], ",", System`RowBox[{System`RowBox[{"list", 
                          "[", System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{"2", ",", System`RowBox[{"d", "[", 
                          "1", "]"}]}], "]"}], ",", System`RowBox[{"d0", "[", 
                          "3", "]"}]}], "]"}], "\[Rule]", "0.`"}], ",", 
                      System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{"2", ",", System`RowBox[{"d0", "[", 
                          "0", "]"}]}], "]"}], ",", System`RowBox[{"d0", "[", 
                          "3", "]"}]}], "]"}], "\[Rule]", "0.`"}], ",", 
                      System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{"3", ",", "wsmooth"}], "]"}], ",", 
                          System`RowBox[{"d0", "[", "3", "]"}]}], "]"}], 
                        "\[Rule]", "0.`"}], ",", System`RowBox[{System`RowBox[
                         {"list", "[", System`RowBox[{System`RowBox[{"list", 
                          "[", System`RowBox[{"3", ",", "wdata"}], "]"}], 
                          ",", System`RowBox[{"d0", "[", "3", "]"}]}], "]"}], 
                        "\[Rule]", "0.`"}], ",", System`RowBox[{System`RowBox[
                         {"list", "[", System`RowBox[{System`RowBox[{"list", 
                          "[", System`RowBox[{"3", ",", System`RowBox[{"d", 
                          "[", System`RowBox[{"-", "1"}], "]"}]}], "]"}], 
                          ",", System`RowBox[{"d0", "[", "3", "]"}]}], "]"}], 
                        "\[Rule]", "0.`"}], ",", System`RowBox[{System`RowBox[
                         {"list", "[", System`RowBox[{System`RowBox[{"list", 
                          "[", System`RowBox[{"3", ",", System`RowBox[{"d", 
                          "[", "0", "]"}]}], "]"}], ",", System`RowBox[
                          {"d0", "[", "3", "]"}]}], "]"}], "\[Rule]", 
                        "0.`"}], ",", System`RowBox[{System`RowBox[{"list", 
                          "[", System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{"3", ",", System`RowBox[{"d", "[", 
                          "1", "]"}]}], "]"}], ",", System`RowBox[{"d0", "[", 
                          "3", "]"}]}], "]"}], "\[Rule]", "0.`"}], ",", 
                      System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{"3", ",", System`RowBox[{"d0", "[", 
                          "0", "]"}]}], "]"}], ",", System`RowBox[{"d0", "[", 
                          "3", "]"}]}], "]"}], "\[Rule]", "1.`"}], ",", 
                      System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{"4", ",", "wsmooth"}], "]"}], ",", 
                          System`RowBox[{"d0", "[", "3", "]"}]}], "]"}], 
                        "\[Rule]", "0.`"}], ",", System`RowBox[{System`RowBox[
                         {"list", "[", System`RowBox[{System`RowBox[{"list", 
                          "[", System`RowBox[{"4", ",", "wdata"}], "]"}], 
                          ",", System`RowBox[{"d0", "[", "3", "]"}]}], "]"}], 
                        "\[Rule]", "0.`"}], ",", System`RowBox[{System`RowBox[
                         {"list", "[", System`RowBox[{System`RowBox[{"list", 
                          "[", System`RowBox[{"4", ",", System`RowBox[{"d", 
                          "[", System`RowBox[{"-", "1"}], "]"}]}], "]"}], 
                          ",", System`RowBox[{"d0", "[", "3", "]"}]}], "]"}], 
                        "\[Rule]", "0.`"}], ",", System`RowBox[{System`RowBox[
                         {"list", "[", System`RowBox[{System`RowBox[{"list", 
                          "[", System`RowBox[{"4", ",", System`RowBox[{"d", 
                          "[", "0", "]"}]}], "]"}], ",", System`RowBox[
                          {"d0", "[", "3", "]"}]}], "]"}], "\[Rule]", 
                        "0.`"}], ",", System`RowBox[{System`RowBox[{"list", 
                          "[", System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{"4", ",", System`RowBox[{"d", "[", 
                          "1", "]"}]}], "]"}], ",", System`RowBox[{"d0", "[", 
                          "3", "]"}]}], "]"}], "\[Rule]", "0.`"}], ",", 
                      System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{"4", ",", System`RowBox[{"d0", "[", 
                          "0", "]"}]}], "]"}], ",", System`RowBox[{"d0", "[", 
                          "3", "]"}]}], "]"}], "\[Rule]", "0.`"}], ",", 
                      System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{"2", ",", "wsmooth"}], "]"}], ",", 
                          System`RowBox[{"d0", "[", "4", "]"}]}], "]"}], 
                        "\[Rule]", "0.`"}], ",", System`RowBox[{System`RowBox[
                         {"list", "[", System`RowBox[{System`RowBox[{"list", 
                          "[", System`RowBox[{"2", ",", "wdata"}], "]"}], 
                          ",", System`RowBox[{"d0", "[", "4", "]"}]}], "]"}], 
                        "\[Rule]", "0.`"}], ",", System`RowBox[{System`RowBox[
                         {"list", "[", System`RowBox[{System`RowBox[{"list", 
                          "[", System`RowBox[{"2", ",", System`RowBox[{"d", 
                          "[", System`RowBox[{"-", "1"}], "]"}]}], "]"}], 
                          ",", System`RowBox[{"d0", "[", "4", "]"}]}], "]"}], 
                        "\[Rule]", "0.`"}], ",", System`RowBox[{System`RowBox[
                         {"list", "[", System`RowBox[{System`RowBox[{"list", 
                          "[", System`RowBox[{"2", ",", System`RowBox[{"d", 
                          "[", "0", "]"}]}], "]"}], ",", System`RowBox[
                          {"d0", "[", "4", "]"}]}], "]"}], "\[Rule]", 
                        "0.`"}], ",", System`RowBox[{System`RowBox[{"list", 
                          "[", System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{"2", ",", System`RowBox[{"d", "[", 
                          "1", "]"}]}], "]"}], ",", System`RowBox[{"d0", "[", 
                          "4", "]"}]}], "]"}], "\[Rule]", "0.`"}], ",", 
                      System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{"2", ",", System`RowBox[{"d0", "[", 
                          "0", "]"}]}], "]"}], ",", System`RowBox[{"d0", "[", 
                          "4", "]"}]}], "]"}], "\[Rule]", "0.`"}], ",", 
                      System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{"3", ",", "wsmooth"}], "]"}], ",", 
                          System`RowBox[{"d0", "[", "4", "]"}]}], "]"}], 
                        "\[Rule]", "0.`"}], ",", System`RowBox[{System`RowBox[
                         {"list", "[", System`RowBox[{System`RowBox[{"list", 
                          "[", System`RowBox[{"3", ",", "wdata"}], "]"}], 
                          ",", System`RowBox[{"d0", "[", "4", "]"}]}], "]"}], 
                        "\[Rule]", "0.`"}], ",", System`RowBox[{System`RowBox[
                         {"list", "[", System`RowBox[{System`RowBox[{"list", 
                          "[", System`RowBox[{"3", ",", System`RowBox[{"d", 
                          "[", System`RowBox[{"-", "1"}], "]"}]}], "]"}], 
                          ",", System`RowBox[{"d0", "[", "4", "]"}]}], "]"}], 
                        "\[Rule]", "0.`"}], ",", System`RowBox[{System`RowBox[
                         {"list", "[", System`RowBox[{System`RowBox[{"list", 
                          "[", System`RowBox[{"3", ",", System`RowBox[{"d", 
                          "[", "0", "]"}]}], "]"}], ",", System`RowBox[
                          {"d0", "[", "4", "]"}]}], "]"}], "\[Rule]", 
                        "0.`"}], ",", System`RowBox[{System`RowBox[{"list", 
                          "[", System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{"3", ",", System`RowBox[{"d", "[", 
                          "1", "]"}]}], "]"}], ",", System`RowBox[{"d0", "[", 
                          "4", "]"}]}], "]"}], "\[Rule]", "0.`"}], ",", 
                      System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{"3", ",", System`RowBox[{"d0", "[", 
                          "0", "]"}]}], "]"}], ",", System`RowBox[{"d0", "[", 
                          "4", "]"}]}], "]"}], "\[Rule]", "0.`"}], ",", 
                      System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{"4", ",", "wsmooth"}], "]"}], ",", 
                          System`RowBox[{"d0", "[", "4", "]"}]}], "]"}], 
                        "\[Rule]", "0.`"}], ",", System`RowBox[{System`RowBox[
                         {"list", "[", System`RowBox[{System`RowBox[{"list", 
                          "[", System`RowBox[{"4", ",", "wdata"}], "]"}], 
                          ",", System`RowBox[{"d0", "[", "4", "]"}]}], "]"}], 
                        "\[Rule]", "0.`"}], ",", System`RowBox[{System`RowBox[
                         {"list", "[", System`RowBox[{System`RowBox[{"list", 
                          "[", System`RowBox[{"4", ",", System`RowBox[{"d", 
                          "[", System`RowBox[{"-", "1"}], "]"}]}], "]"}], 
                          ",", System`RowBox[{"d0", "[", "4", "]"}]}], "]"}], 
                        "\[Rule]", "0.`"}], ",", System`RowBox[{System`RowBox[
                         {"list", "[", System`RowBox[{System`RowBox[{"list", 
                          "[", System`RowBox[{"4", ",", System`RowBox[{"d", 
                          "[", "0", "]"}]}], "]"}], ",", System`RowBox[
                          {"d0", "[", "4", "]"}]}], "]"}], "\[Rule]", 
                        "0.`"}], ",", System`RowBox[{System`RowBox[{"list", 
                          "[", System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{"4", ",", System`RowBox[{"d", "[", 
                          "1", "]"}]}], "]"}], ",", System`RowBox[{"d0", "[", 
                          "4", "]"}]}], "]"}], "\[Rule]", "0.`"}], ",", 
                      System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{"4", ",", System`RowBox[{"d0", "[", 
                          "0", "]"}]}], "]"}], ",", System`RowBox[{"d0", "[", 
                          "4", "]"}]}], "]"}], "\[Rule]", "1.`"}], ",", 
                      System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{"2", ",", "wsmooth"}], "]"}], ",", 
                          "wdata"}], "]"}], "\[Rule]", "0.`"}], ",", 
                      System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{"2", ",", "wdata"}], "]"}], ",", 
                          "wdata"}], "]"}], "\[Rule]", "1.`"}], ",", 
                      System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{"2", ",", System`RowBox[{"d", "[", 
                          System`RowBox[{"-", "1"}], "]"}]}], "]"}], ",", 
                          "wdata"}], "]"}], "\[Rule]", "0.`"}], ",", 
                      System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{"2", ",", System`RowBox[{"d", "[", 
                          "0", "]"}]}], "]"}], ",", "wdata"}], "]"}], 
                        "\[Rule]", "0.`"}], ",", System`RowBox[{System`RowBox[
                         {"list", "[", System`RowBox[{System`RowBox[{"list", 
                          "[", System`RowBox[{"2", ",", System`RowBox[{"d", 
                          "[", "1", "]"}]}], "]"}], ",", "wdata"}], "]"}], 
                        "\[Rule]", "0.`"}], ",", System`RowBox[{System`RowBox[
                         {"list", "[", System`RowBox[{System`RowBox[{"list", 
                          "[", System`RowBox[{"2", ",", System`RowBox[{"d0", 
                          "[", "0", "]"}]}], "]"}], ",", "wdata"}], "]"}], 
                        "\[Rule]", "0.`"}], ",", System`RowBox[{System`RowBox[
                         {"list", "[", System`RowBox[{System`RowBox[{"list", 
                          "[", System`RowBox[{"3", ",", "wsmooth"}], "]"}], 
                          ",", "wdata"}], "]"}], "\[Rule]", "0.`"}], ",", 
                      System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{"3", ",", "wdata"}], "]"}], ",", 
                          "wdata"}], "]"}], "\[Rule]", "1.`"}], ",", 
                      System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{"3", ",", System`RowBox[{"d", "[", 
                          System`RowBox[{"-", "1"}], "]"}]}], "]"}], ",", 
                          "wdata"}], "]"}], "\[Rule]", "0.`"}], ",", 
                      System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{"3", ",", System`RowBox[{"d", "[", 
                          "0", "]"}]}], "]"}], ",", "wdata"}], "]"}], 
                        "\[Rule]", "0.`"}], ",", System`RowBox[{System`RowBox[
                         {"list", "[", System`RowBox[{System`RowBox[{"list", 
                          "[", System`RowBox[{"3", ",", System`RowBox[{"d", 
                          "[", "1", "]"}]}], "]"}], ",", "wdata"}], "]"}], 
                        "\[Rule]", "0.`"}], ",", System`RowBox[{System`RowBox[
                         {"list", "[", System`RowBox[{System`RowBox[{"list", 
                          "[", System`RowBox[{"3", ",", System`RowBox[{"d0", 
                          "[", "0", "]"}]}], "]"}], ",", "wdata"}], "]"}], 
                        "\[Rule]", "0.`"}], ",", System`RowBox[{System`RowBox[
                         {"list", "[", System`RowBox[{System`RowBox[{"list", 
                          "[", System`RowBox[{"4", ",", "wsmooth"}], "]"}], 
                          ",", "wdata"}], "]"}], "\[Rule]", "0.`"}], ",", 
                      System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{"4", ",", "wdata"}], "]"}], ",", 
                          "wdata"}], "]"}], "\[Rule]", "1.`"}], ",", 
                      System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{"4", ",", System`RowBox[{"d", "[", 
                          System`RowBox[{"-", "1"}], "]"}]}], "]"}], ",", 
                          "wdata"}], "]"}], "\[Rule]", "0.`"}], ",", 
                      System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{"4", ",", System`RowBox[{"d", "[", 
                          "0", "]"}]}], "]"}], ",", "wdata"}], "]"}], 
                        "\[Rule]", "0.`"}], ",", System`RowBox[{System`RowBox[
                         {"list", "[", System`RowBox[{System`RowBox[{"list", 
                          "[", System`RowBox[{"4", ",", System`RowBox[{"d", 
                          "[", "1", "]"}]}], "]"}], ",", "wdata"}], "]"}], 
                        "\[Rule]", "0.`"}], ",", System`RowBox[{System`RowBox[
                         {"list", "[", System`RowBox[{System`RowBox[{"list", 
                          "[", System`RowBox[{"4", ",", System`RowBox[{"d0", 
                          "[", "0", "]"}]}], "]"}], ",", "wdata"}], "]"}], 
                        "\[Rule]", "0.`"}], ",", System`RowBox[{System`RowBox[
                         {"list", "[", System`RowBox[{System`RowBox[{"list", 
                          "[", System`RowBox[{"2", ",", "wsmooth"}], "]"}], 
                          ",", "wsmooth"}], "]"}], "\[Rule]", "1.`"}], ",", 
                      System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{"2", ",", "wdata"}], "]"}], ",", 
                          "wsmooth"}], "]"}], "\[Rule]", "0.`"}], ",", 
                      System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{"2", ",", System`RowBox[{"d", "[", 
                          System`RowBox[{"-", "1"}], "]"}]}], "]"}], ",", 
                          "wsmooth"}], "]"}], "\[Rule]", "0.`"}], ",", 
                      System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{"2", ",", System`RowBox[{"d", "[", 
                          "0", "]"}]}], "]"}], ",", "wsmooth"}], "]"}], 
                        "\[Rule]", "0.`"}], ",", System`RowBox[{System`RowBox[
                         {"list", "[", System`RowBox[{System`RowBox[{"list", 
                          "[", System`RowBox[{"2", ",", System`RowBox[{"d", 
                          "[", "1", "]"}]}], "]"}], ",", "wsmooth"}], "]"}], 
                        "\[Rule]", "0.`"}], ",", System`RowBox[{System`RowBox[
                         {"list", "[", System`RowBox[{System`RowBox[{"list", 
                          "[", System`RowBox[{"2", ",", System`RowBox[{"d0", 
                          "[", "0", "]"}]}], "]"}], ",", "wsmooth"}], "]"}], 
                        "\[Rule]", "0.`"}], ",", System`RowBox[{System`RowBox[
                         {"list", "[", System`RowBox[{System`RowBox[{"list", 
                          "[", System`RowBox[{"3", ",", "wsmooth"}], "]"}], 
                          ",", "wsmooth"}], "]"}], "\[Rule]", "1.`"}], ",", 
                      System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{"3", ",", "wdata"}], "]"}], ",", 
                          "wsmooth"}], "]"}], "\[Rule]", "0.`"}], ",", 
                      System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{"3", ",", System`RowBox[{"d", "[", 
                          System`RowBox[{"-", "1"}], "]"}]}], "]"}], ",", 
                          "wsmooth"}], "]"}], "\[Rule]", "0.`"}], ",", 
                      System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{"3", ",", System`RowBox[{"d", "[", 
                          "0", "]"}]}], "]"}], ",", "wsmooth"}], "]"}], 
                        "\[Rule]", "0.`"}], ",", System`RowBox[{System`RowBox[
                         {"list", "[", System`RowBox[{System`RowBox[{"list", 
                          "[", System`RowBox[{"3", ",", System`RowBox[{"d", 
                          "[", "1", "]"}]}], "]"}], ",", "wsmooth"}], "]"}], 
                        "\[Rule]", "0.`"}], ",", System`RowBox[{System`RowBox[
                         {"list", "[", System`RowBox[{System`RowBox[{"list", 
                          "[", System`RowBox[{"3", ",", System`RowBox[{"d0", 
                          "[", "0", "]"}]}], "]"}], ",", "wsmooth"}], "]"}], 
                        "\[Rule]", "0.`"}], ",", System`RowBox[{System`RowBox[
                         {"list", "[", System`RowBox[{System`RowBox[{"list", 
                          "[", System`RowBox[{"4", ",", "wsmooth"}], "]"}], 
                          ",", "wsmooth"}], "]"}], "\[Rule]", "1.`"}], ",", 
                      System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{"4", ",", "wdata"}], "]"}], ",", 
                          "wsmooth"}], "]"}], "\[Rule]", "0.`"}], ",", 
                      System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{"4", ",", System`RowBox[{"d", "[", 
                          System`RowBox[{"-", "1"}], "]"}]}], "]"}], ",", 
                          "wsmooth"}], "]"}], "\[Rule]", "0.`"}], ",", 
                      System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{"4", ",", System`RowBox[{"d", "[", 
                          "0", "]"}]}], "]"}], ",", "wsmooth"}], "]"}], 
                        "\[Rule]", "0.`"}], ",", System`RowBox[{System`RowBox[
                         {"list", "[", System`RowBox[{System`RowBox[{"list", 
                          "[", System`RowBox[{"4", ",", System`RowBox[{"d", 
                          "[", "1", "]"}]}], "]"}], ",", "wsmooth"}], "]"}], 
                        "\[Rule]", "0.`"}], ",", System`RowBox[{System`RowBox[
                         {"list", "[", System`RowBox[{System`RowBox[{"list", 
                          "[", System`RowBox[{"4", ",", System`RowBox[{"d0", 
                          "[", "0", "]"}]}], "]"}], ",", "wsmooth"}], "]"}], 
                        "\[Rule]", "0.`"}]}], "}"}], ",", "True", ",", 
                  System`RowBox[{"{", System`RowBox[{System`RowBox[{"{", 
                        System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{"2", ",", "wsmooth"}], "]"}], ",", 
                          System`RowBox[{"list", "[", System`RowBox[{"2", 
                          ",", "wdata"}], "]"}], ",", System`RowBox[{"list", 
                          "[", System`RowBox[{"2", ",", System`RowBox[{"d", 
                          "[", System`RowBox[{"-", "1"}], "]"}]}], "]"}], 
                          ",", System`RowBox[{"list", "[", System`RowBox[
                          {"2", ",", System`RowBox[{"d", "[", "0", "]"}]}], 
                          "]"}], ",", System`RowBox[{"list", "[", 
                          System`RowBox[{"2", ",", System`RowBox[{"d", "[", 
                          "1", "]"}]}], "]"}], ",", System`RowBox[{"list", 
                          "[", System`RowBox[{"2", ",", System`RowBox[{"d0", 
                          "[", "0", "]"}]}], "]"}], ",", System`RowBox[
                          {"list", "[", System`RowBox[{"3", ",", "wsmooth"}], 
                          "]"}], ",", System`RowBox[{"list", "[", 
                          System`RowBox[{"3", ",", "wdata"}], "]"}], ",", 
                          System`RowBox[{"list", "[", System`RowBox[{"3", 
                          ",", System`RowBox[{"d", "[", System`RowBox[{"-", 
                          "1"}], "]"}]}], "]"}], ",", System`RowBox[{"list", 
                          "[", System`RowBox[{"3", ",", System`RowBox[{"d", 
                          "[", "0", "]"}]}], "]"}], ",", System`RowBox[
                          {"list", "[", System`RowBox[{"3", ",", 
                          System`RowBox[{"d", "[", "1", "]"}]}], "]"}], ",", 
                          System`RowBox[{"list", "[", System`RowBox[{"3", 
                          ",", System`RowBox[{"d0", "[", "0", "]"}]}], "]"}], 
                          ",", System`RowBox[{"list", "[", System`RowBox[
                          {"4", ",", "wsmooth"}], "]"}], ",", System`RowBox[
                          {"list", "[", System`RowBox[{"4", ",", "wdata"}], 
                          "]"}], ",", System`RowBox[{"list", "[", 
                          System`RowBox[{"4", ",", System`RowBox[{"d", "[", 
                          System`RowBox[{"-", "1"}], "]"}]}], "]"}], ",", 
                          System`RowBox[{"list", "[", System`RowBox[{"4", 
                          ",", System`RowBox[{"d", "[", "0", "]"}]}], "]"}], 
                          ",", System`RowBox[{"list", "[", System`RowBox[
                          {"4", ",", System`RowBox[{"d", "[", "1", "]"}]}], 
                          "]"}], ",", System`RowBox[{"list", "[", 
                          System`RowBox[{"4", ",", System`RowBox[{"d0", "[", 
                          "0", "]"}]}], "]"}]}], "}"}], ",", System`RowBox[
                       {"{", System`RowBox[{System`RowBox[{"list", "[", 
                          System`RowBox[{"2", ",", System`RowBox[{"{", "1", 
                          "}"}]}], "]"}], ",", System`RowBox[{"list", "[", 
                          System`RowBox[{"2", ",", System`RowBox[{"{", "2", 
                          "}"}]}], "]"}], ",", System`RowBox[{"list", "[", 
                          System`RowBox[{"3", ",", System`RowBox[{"{", "1", 
                          "}"}]}], "]"}], ",", System`RowBox[{"list", "[", 
                          System`RowBox[{"3", ",", System`RowBox[{"{", "2", 
                          "}"}]}], "]"}], ",", System`RowBox[{"list", "[", 
                          System`RowBox[{"4", ",", System`RowBox[{"{", "1", 
                          "}"}]}], "]"}], ",", System`RowBox[{"list", "[", 
                          System`RowBox[{"4", ",", System`RowBox[{"{", "2", 
                          "}"}]}], "]"}]}], "}"}], ",", System`RowBox[
                       {"{", System`RowBox[{System`RowBox[{"d", "[", "1", 
                          "]"}], ",", System`RowBox[{"d", "[", "2", "]"}], 
                          ",", System`RowBox[{"d", "[", "3", "]"}], ",", 
                          System`RowBox[{"d", "[", "4", "]"}], ",", 
                          System`RowBox[{"d", "[", "5", "]"}], ",", 
                          System`RowBox[{"d0", "[", "2", "]"}], ",", 
                          System`RowBox[{"d0", "[", "3", "]"}], ",", 
                          System`RowBox[{"d0", "[", "4", "]"}], ",", "wdata", 
                          ",", "wsmooth"}], "}"}], ",", "True"}], "}"}]}], 
                "}"}]}]}]}], "\[IndentingNewLine]", "]"}]}], 
    "\[IndentingNewLine]", "]"}]], "Input", System`CellChangeTimes -> 
  {{3.6816688825522084*^9, 3.6816689238107166*^9}, {3.6816689568699865*^9, 
  3.6816689742026243*^9}, {3.681669781253157*^9, 3.6816698936724987*^9}, 
  {3.6816700276657734*^9, 3.681670078589351*^9}}]
