Cell[BoxData[RowBox[{"Persist", "[", RowBox[{"\"Scene2DShow\"", ",", 
      "\[IndentingNewLine]", "\[IndentingNewLine]", 
      RowBox[{"(*", RowBox[{" ", RowBox[{RowBox[{"TODO", " ", "show", " ", 
              "all", " ", "images", " ", "in", " ", "the", " ", "same", " ", 
              "orientation"}], ",", " ", RowBox[{"show", " ", "multiple", 
              " ", "things", " ", "at", " ", "once", " ", "like", " ", 
              "vsfs2d`"}], ",", " ", RowBox[{RowBox[{"show", " ", "light", 
                " ", "direction", " ", "and", " ", "dimensions", 
                "\[IndentingNewLine]", "\[IndentingNewLine]", "TODO", " ", 
                "cannot", " ", "show", " ", "all", " ", "ticks", " ", "for", 
                " ", "large", " ", "scenes"}], " ", "-", " ", 
              RowBox[{"use", " ", "auto", " ", "heuristics", " ", 
                RowBox[{"afterall", "\[IndentingNewLine]", 
                  "\[IndentingNewLine]", ":"}]}]}]}], ")"}], 
        "\[IndentingNewLine]", "*)"}], "\[IndentingNewLine]", 
      RowBox[{RowBox[{"RedefinePublicFunction", "[", "\[IndentingNewLine]", 
          RowBox[{RowBox[{"Scene2DShow", "[", "s_Scene2D", "]"}], 
            "\[IndentingNewLine]", ",", "\"Interactively visualizes various \
properties of a Scene2D object.\"", "\[IndentingNewLine]", ",", 
            RowBox[{"Manipulate", "[", "\[IndentingNewLine]", 
              RowBox[{RowBox[{"Switch", "[", RowBox[{"which", 
                    "\[IndentingNewLine]", ",", "\"a\"", ",", RowBox[
                     {"Framed", "@", RowBox[{"Scene2DShowAlbedo", "@", 
                        "s"}]}], "\[IndentingNewLine]", ",", "\"c\"", ",", 
                    RowBox[{"Framed", "@", RowBox[{"Scene2DShowColor", "@", 
                        "s"}]}], "\[IndentingNewLine]", ",", "\"diffuse\"", 
                    ",", RowBox[{"Framed", "@", RowBox[{"Scene2DShowColor", 
                        "[", RowBox[{"s", ",", "\"diffuse\""}], "]"}]}], 
                    "\[IndentingNewLine]", ",", RowBox[{"\"d\"", "|", 
                      "\"doriginal\"", "|", "\"dsharp\""}], ",", RowBox[
                     {"Scene2DShowDistanceField", "[", RowBox[{"s", ",", 
                        "which"}], "]"}], "\[IndentingNewLine]", ",", 
                    "\"normalSharp\"", ",", RowBox[{"ListNormalVectorPlot", 
                      "@", RowBox[{"s", "@", "\"normalSharp\""}]}]}], 
                  "\[IndentingNewLine]", "]"}], "\[IndentingNewLine]", ",", 
                RowBox[{"{", RowBox[{"which", ",", RowBox[
                     {"Scene2DGridDataNames", "@", "s"}]}], "}"}], 
                "\[IndentingNewLine]", ",", RowBox[{"TrackedSymbols", 
                  "\[RuleDelayed]", "which"}]}], "]"}]}], 
          "\[IndentingNewLine]", "]"}], ";"}]}], "\[IndentingNewLine]", 
    "\[IndentingNewLine]", "]"}]], "Input", GeneratedCell -> True, 
 CellAutoOverwrite -> True, CellChangeTimes -> 
  {{3.6805635175748672*^9, 3.6805635864137363*^9}, 
   {3.68056362122238*^9, 3.680563877380669*^9}, 3.6805646354811754*^9, 
   {3.6805705376990747*^9, 3.680570550007389*^9}, 3.6805996156301575*^9}]
