Cell[BoxData[RowBox[{"Persist", "[", "\[IndentingNewLine]", 
    RowBox[{"\"SOPObjectiveVector\"", "\[IndentingNewLine]", 
      "\[IndentingNewLine]", ",", "\[IndentingNewLine]", 
      RowBox[{RowBox[{"RedefinePublicFunction", "[", "\[IndentingNewLine]", 
          RowBox[{RowBox[{"SOPObjectiveVector", "[", 
              "p_SparseOptimizationProblem", "]"}], "\[IndentingNewLine]", 
            ",", "\"with data-y inserted, this is the objective optimized\"", 
            "\[IndentingNewLine]", ",", RowBox[{RowBox[{"{", RowBox[
                 {"dataWithouty", "=", RowBox[{"DeleteCases", "[", 
                    RowBox[{RowBox[{"SOPDataAsRules", "@", "p"}], ",", 
                      RowBox[{RowBox[{"HoldPattern", "[", RowBox[{"v_", 
                          "\[Rule]", "_"}], "]"}], "/;", RowBox[{"MemberQ", 
                          "[", RowBox[{RowBox[{"SOPGetY", "@", "p"}], ",", 
                          "v"}], "]"}]}]}], "]"}]}], "}"}], "~", "With", "~", 
              RowBox[{"(", RowBox[{RowBox[{"SOPFullyAbstractObjectiveVector", 
                    "[", "p", "]"}], "/.", "dataWithouty"}], ")"}]}]}], 
          "\[IndentingNewLine]", "]"}], ";"}]}], "\[IndentingNewLine]", 
    "]"}]], "Input", CellChangeTimes -> 
  {{3.680596448127592*^9, 3.6805964559533396*^9}, 
   {3.6805965077750015*^9, 3.680596617194547*^9}, 
   {3.6805966555504074*^9, 3.680596721436619*^9}, 
   {3.680596752742683*^9, 3.6805968091390343*^9}}]
