System`Cell[System`BoxData[System`RowBox[
   {System`RowBox[{"PRedefinePublicFunction", "[", "\[IndentingNewLine]", 
      System`RowBox[{System`RowBox[{System`RowBox[{"SOP`SOPFx", "[", 
            System`RowBox[{"p_SparseOptimizationProblem", 
              "\[IndentingNewLine]", ",", System`RowBox[{"x", ":", "_List", 
                System`RowBox[{"(*", System`RowBox[{"should", " ", "be", " ", 
                    "TODO", " ", System`RowBox[{"{", "__Real", "}"}]}], 
                  "*)"}], ":", System`RowBox[{"{", "}"}]}]}], "]"}], "/;", 
          System`RowBox[{System`RowBox[{System`RowBox[{"Length", "@", "x"}], 
              "===", "0"}], "||", System`RowBox[{System`RowBox[{"Length", 
                "@", "x"}], "===", System`RowBox[{"Length", "@", 
                System`RowBox[{"SOPGetX0", "[", "p", "]"}]}]}]}]}], 
        "\[IndentingNewLine]", "\[IndentingNewLine]", ",", 
        "\"F(x) for the stored x0 or for a user-specified x\"", ",", 
        "\[IndentingNewLine]", "\[IndentingNewLine]", 
        System`RowBox[{"Flatten", "@", System`RowBox[{"SOPEnergyVector", "[", 
            System`RowBox[{"p", ",", System`RowBox[{"If", "[", System`RowBox[
                 {System`RowBox[{"x", "===", System`RowBox[{"{", "}"}]}], 
                  ",", System`RowBox[{"SOPGetX0", "[", "p", "]"}], ",", 
                  "x"}], "]"}]}], "]"}]}]}], "\[IndentingNewLine]", 
      "\[IndentingNewLine]", "]"}], ";"}]], "Input", 
 System`CellChangeTimes -> {{3.681129289477418*^9, 3.6811293054220524*^9}, 
  {3.681147800980341*^9, 3.681147813127285*^9}, {3.681147856199168*^9, 
  3.6811478615644855*^9}}, System`CellTags -> 
  "depersistedCell3dccaa88-dab6-4242-a89f-0eaebfa1f5a1"]
