Cell[BoxData[RowBox[{"Persist", "[", "\[IndentingNewLine]", 
    RowBox[{"\"SceneXAtomRuleCoordinateBoundsFor\"", "\[IndentingNewLine]", 
      "\[IndentingNewLine]", ",", "\[IndentingNewLine]", 
      "\[IndentingNewLine]", RowBox[{RowBox[{"RedefinePublicFunction", "[", 
          "\[IndentingNewLine]", RowBox[
           {RowBox[{"SceneXAtomRuleCoordinateBoundsFor", "[", 
              RowBox[{"s_Symbol", ",", RowBox[{"data", ":", 
                  "$SceneXEnergyDataPattern"}]}], "]"}], 
            "\[IndentingNewLine]", "\[IndentingNewLine]", ",", 
            "\"defined coordinateBounds\"", "\[IndentingNewLine]", 
            "\[IndentingNewLine]", ",", RowBox[{"CoordinateBounds", "@", 
              RowBox[{"SceneXAtomRulePositionsFor", "[", RowBox[{"s", ",", 
                  "data"}], "]"}]}], "\[IndentingNewLine]", 
            "\[IndentingNewLine]", ",", RowBox[{"{", RowBox[{RowBox[
                 {"{", "__Integer", "}"}], "..."}], "}"}]}], 
          "\[IndentingNewLine]", "]"}], ";"}]}], "\[IndentingNewLine]", 
    "\[IndentingNewLine]", "]"}]], "Input", 
 CellChangeTimes -> {{3.680596448127592*^9, 3.6805964559533396*^9}, 
   {3.6805965077750015*^9, 3.680596617194547*^9}, 
   {3.6805966555504074*^9, 3.6805966996634493*^9}}]
