HoldComplete[RedefinePublicFunction[Scene2DEnhance[s_Scene2D, 
   weights:$SceneXEnergyWeightPattern], "enhances d and a to be more \
consistent with the lighting generated by the lighting model", 
  Scene2DMakeFromSparseOptimizationProblem[
   SOPSolve[Scene2DSparseOptimizationProblem[s, weights]]]]]
